"use client";
import {tableDaySchedules,tableBookingDescription} from '@/lib/floor-table-schedule';
import {floorTableName} from '@/lib/floor-table-label';
import {useEffect,useId,useMemo,useRef,useState,type ReactNode,type CSSProperties} from 'react';
import {Layers,Plus,ArrowUpRight,Move} from 'lucide-react';
import {areaLevel,areaPlacement,floorLevels,levelName,positionArea,restaurantDayReservations} from '@/lib/restaurant-map';
import {activeReservation,floorAreaAvailability,floorTableScale,type EventArea,type FloorData,type FloorLayout,type FloorTable} from '@/lib/floor-plan';
import {MapNavigation,useMapNavigation} from './map-navigation';
import {FloorTableGraphic} from './floor-table-graphic';
import {OverviewReservations,type OverviewReservationProps} from './overview-reservations';
import {floorMapAreaGeometry,resizeFloorMapArea} from '@/lib/floor-area-bounds';
import {placeMapLabels} from '@/lib/map-labels';
type Props=OverviewReservationProps&{exportLevelId?:string;eventAreas:EventArea[];layout:FloorLayout;data:FloorData;date:string;availabilityDate?:string;time:string;duration:number;editing:boolean;busy:boolean;en:boolean;areaId?:string;selectedTableIds?:string[];detailPanel?:ReactNode;detailTitle?:string;onSelect:(id:string)=>void;onOpen:(id:string,tableId?:string)=>void;onChange:(layout:FloorLayout)=>void;tableState:(table:FloorTable)=>string};
export function RestaurantOverview({exportLevelId,layout,data,date,availabilityDate=date,time,duration,editing,busy,en,areaId,onSelect,onOpen,onChange,tableState,eventAreas,selectedTableIds,detailPanel,detailTitle,...reservationProps}:Props){
 const say=(es:string,eng:string)=>en?eng:es,levels=floorLevels(layout),pattern=useId().replace(/:/g,''),svg=useRef<SVGSVGElement>(null);
 const [level,setLevel]=useState(()=>{const a=layout.areas.find(a=>a.id===areaId);return a?areaLevel(layout,a):levels[0].id}),[focused,setFocused]=useState<string|null>(null);
 const sidebar=useRef<HTMLDivElement>(null),[resizeArea,setResizeArea]=useState<string|null>(null);
 const bookings=useMemo(()=>restaurantDayReservations(data,date,eventAreas),[data,date,eventAreas]);
 const focusedBooking=bookings.find(b=>b.reservation.id===focused);
 const schedules=useMemo(()=>tableDaySchedules(data,date,reservationProps.timeFormat),[data,date,reservationProps.timeFormat]);
 const counts=useMemo(()=>{const result=new Map<string,number>();for(const b of bookings){if(!activeReservation(b.reservation))continue;for(const id of b.tableIds)result.set(id,(result.get(id)||0)+1)}return result},[bookings]);
 const activeLevel=levels.find(l=>l.id===(exportLevelId||level))||levels[0],areas=layout.areas.filter(a=>areaLevel(layout,a)===activeLevel.id),selected=areas.find(a=>a.id===areaId);
 const labels=useMemo(()=>{
  const rooms=layout.areas.filter(a=>areaLevel(layout,a)===activeLevel.id).map(a=>{const geometry=floorMapAreaGeometry(layout,a);return {id:a.id,name:a.name,...geometry.frame}});
  const tables=rooms.flatMap(a=>layout.tables.filter(t=>t.areaId===a.id).map(t=>{const canvas=floorMapAreaGeometry(layout,layout.areas.find(area=>area.id===a.id)!).canvas,w=(canvas.width-16)/1000,h=(canvas.height-58)/650,size=floorTableScale(t);return {x:canvas.x+8+t.x*10*w-90*size*w,y:canvas.y+32+t.y*6.5*h-90*size*h,width:180*size*w,height:200*size*h}}));
  return placeMapLabels(rooms,tables);
 },[layout,activeLevel.id]);
 const mapBounds=useMemo(()=>{
  if(editing||!areas.length)return {x:0,y:0,width:1100,height:760};
  const boxes=areas.map(a=>{return floorMapAreaGeometry(layout,a).frame}).concat(labels.map(l=>({x:l.x,y:l.y,width:l.width,height:l.height})));
  const x=Math.min(...boxes.map(b=>b.x))-24,y=Math.min(...boxes.map(b=>b.y))-24;
  return {x,y,width:Math.max(280,Math.max(...boxes.map(b=>b.x+b.width))-x+24),height:Math.max(220,Math.max(...boxes.map(b=>b.y+b.height))-y+24)};
 },[layout,labels,activeLevel.id,editing]);
 const drag=useRef<{id:string;x:number;y:number;width:number;height:number;startX:number;startY:number;resize:boolean;pointerId:number;layout:FloorLayout;geometry:ReturnType<typeof floorMapAreaGeometry>}|null>(null);
 const cancelDrag=()=>{const d=drag.current;drag.current=null;if(d)onChange(d.layout);setResizeArea(null)};
 const map=useMapNavigation(editing,cancelDrag);
 useEffect(()=>setResizeArea(null),[editing,areaId,activeLevel.id,map.hand]);
 const point=(e:React.PointerEvent)=>{const matrix=svg.current?.getScreenCTM();return matrix?new DOMPoint(e.clientX,e.clientY).matrixTransform(matrix.inverse()):null};
 const update=(id:string,patch:Parameters<typeof positionArea>[2])=>onChange(positionArea(layout,id,patch));
 const beginDrag=(e:React.PointerEvent<SVGElement>,id:string,resize=false)=>{if(!editing||busy||map.hand||e.button!==0)return;const at=point(e),a=layout.areas.find(a=>a.id===id);if(!at||!a)return;e.preventDefault();if(!resize)setResizeArea(null);onSelect(id);svg.current?.setPointerCapture(e.pointerId);drag.current={id,pointerId:e.pointerId,layout,...areaPlacement(layout,a),startX:at.x,startY:at.y,resize,geometry:floorMapAreaGeometry(layout,a)}};
 const moveDrag=(e:React.PointerEvent<SVGElement>)=>{const d=drag.current,at=point(e);if(!d||!at||busy||d.pointerId!==e.pointerId)return;const dx=(at.x-d.startX)/11,dy=(at.y-d.startY)/7.6;update(d.id,d.resize?resizeFloorMapArea(d.geometry,d.geometry.frame.width+at.x-d.startX,d.geometry.frame.height+at.y-d.startY):{x:d.x+dx,y:d.y+dy})};
 const endDrag=(e:React.PointerEvent<SVGElement>)=>{if(drag.current?.pointerId!==e.pointerId)return;drag.current=null;setResizeArea(null);if(svg.current?.hasPointerCapture(e.pointerId))svg.current.releasePointerCapture(e.pointerId)};
 const totals=areas.reduce((n,a)=>{const state=floorAreaAvailability(data,a.id,availabilityDate,time,duration);return {tables:n.tables+layout.tables.filter(t=>t.areaId===a.id).length,free:n.free+state.available,seats:n.seats+layout.tables.filter(t=>t.areaId===a.id).reduce((s,t)=>s+t.seats,0)}},{tables:0,free:0,seats:0});
 function addLevel(){if(busy||levels.length>=10)return;let number=levels.length+1;while(levels.some(l=>l.name===`Nivel ${number}`))number++;const id=crypto.randomUUID();onChange({...layout,levels:[...levels,{id,name:`Nivel ${number}`}]});setLevel(id);}
 const drawing=(<svg data-print-level={activeLevel.id} data-print-title={levelName(activeLevel.name,en)} data-print-areas={JSON.stringify(areas.map(a=>a.id))} ref={svg} onPointerMove={moveDrag} onPointerUp={endDrag} onPointerCancel={cancelDrag} style={{width:`${map.zoom*100}%`,minWidth:0,height:`${map.zoom*100}%`}} width={`${map.zoom*100}%`} viewBox={`${mapBounds.x} ${mapBounds.y} ${mapBounds.width} ${mapBounds.height}`} role="group" aria-label={say('Distribución de áreas por nivel','Area layout by level')}>
   <defs><pattern id={pattern} width="25" height="25" patternUnits="userSpaceOnUse"><circle cx="2" cy="2" r="1" fill="#9fb5b2" opacity=".4"/></pattern></defs>
   <rect x="2" y="2" width="1096" height="756" rx="18" fill={`url(#${pattern})`} stroke="#98b5ad" strokeWidth="3"/>
   {/* Paint every room below every table so overlapping areas never cover tables. */}
   {[...areas].sort((a,b)=>Number(a.id===areaId)-Number(b.id===areaId)).map(a=>{
    const p=areaPlacement(layout,a),frame=floorMapAreaGeometry(layout,a).frame,x=frame.x,y=frame.y,w=frame.width,h=frame.height,tables=layout.tables.filter(t=>t.areaId===a.id),availability=floorAreaAvailability(data,a.id,availabilityDate,time,duration),active=a.id===areaId;
    const enter=()=>{onSelect(a.id);if(!editing)onOpen(a.id)};
    return <g key={a.id} data-map-area={a.id}>
     <rect x={x} y={y} width={w} height={h} rx="12" className={`overviewRoom ${a.background==='solid'?'solid':''} ${a.showBorder===false?'borderless':''} ${active&&editing?'selected':''} ${!editing&&availability.full?'full':''}`} role="button" tabIndex={0} aria-pressed={active} aria-label={`${a.name} · ${tables.length} ${say('mesas','tables')}${editing?'':` · ${availability.available} ${say('disponibles','available')}`}`}
      onKeyDown={e=>{if(editing&&!busy&&['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();onSelect(a.id);update(a.id,{x:p.x+(e.key==='ArrowLeft'?-1:e.key==='ArrowRight'?1:0),y:p.y+(e.key==='ArrowUp'?-1:e.key==='ArrowDown'?1:0)})}else if(e.key==='Enter'||e.key===' '){e.preventDefault();enter()}}}
      onClick={()=>{if(!editing)enter()}} onPointerDown={e=>beginDrag(e,a.id)}/>
    </g>;
   })}
   {areas.map(a=>{const p=areaPlacement(layout,a),x=p.x*11,y=p.y*7.6,w=p.width*11,h=p.height*7.6,tables=layout.tables.filter(t=>t.areaId===a.id);
    return <g key={a.id} pointerEvents="none">
     <svg x={x+8} y={y+32} width={w-16} height={h-58} viewBox="0 0 1000 650" preserveAspectRatio="none" style={{width:w-16,height:h-58,pointerEvents:'none'}}>{tables.map(t=><g key={t.id} style={{pointerEvents:editing?'none':'all'}} role={editing?undefined:'button'} tabIndex={editing?undefined:0} data-overview-table={t.id} aria-pressed={!editing&&(selectedTableIds??focusedBooking?.tableIds??[]).includes(t.id)} aria-label={`${a.name} · ${floorTableName(t.name,en)} · ${t.seats} ${say('lugares','seats')} · ${counts.get(t.id)||0} ${say('reservaciones del día','day reservations')} · ${tableBookingDescription(schedules.get(t.id)||[],en)}`} transform={`translate(${t.x*10} ${t.y*6.5})`} onClick={()=>{if(!editing)onOpen(a.id,t.id)}} onKeyDown={e=>{if(!editing&&(e.key==='Enter'||e.key===' ')){e.preventDefault();onOpen(a.id,t.id)}}}>
      <title>{`${a.name} · ${floorTableName(t.name,en)} · ${counts.get(t.id)||0} ${say('reservaciones del día','day reservations')} · ${tableBookingDescription(schedules.get(t.id)||[],en)}`}</title><rect x="-75" y="-75" width="150" height="170" fill="transparent"/><FloorTableGraphic bookings={editing?[]:schedules.get(t.id)} table={t} state={editing?'free':tableState(t)} selected={!editing&&(selectedTableIds??focusedBooking?.tableIds??[]).includes(t.id)} editing={editing} en={en} labelAspect={(w-16)/1000/((h-58)/650)} labelUnit={Math.min((w-16)/1000,(h-58)/650)} compact/>
      {!editing&&!!counts.get(t.id)&&<g pointerEvents="none" transform={`translate(54 -54) scale(${Math.min(1,(h-58)/650/((w-16)/1000))} ${Math.min(1,(w-16)/1000/((h-58)/650))}) translate(-54 54)`}><circle cx="54" cy="-54" r="19" fill="#254e47" stroke="#fff" strokeWidth="2"/><text x="54" y="-47" textAnchor="middle" fill="#fff" fontSize="20" fontWeight="700">{counts.get(t.id)}</text></g>}
     </g>)}</svg>
    </g>;
   })}
   {/* Names are a separate, collision-free layer above ALL rooms and tables. */}
   {labels.filter(l=>l.displaced).map(l=><path key={l.id} d={`M ${l.anchorX} ${l.anchorY} L ${Math.max(l.x,Math.min(l.x+l.width,l.anchorX))} ${Math.max(l.y,Math.min(l.y+l.height,l.anchorY))}`} fill="none" stroke="var(--fp-muted)" strokeWidth="1.5" strokeDasharray="4 4" pointerEvents="none"/>)}
   {labels.map(l=>{const availability=floorAreaAvailability(data,l.id,availabilityDate,time,duration),tables=layout.tables.filter(t=>t.areaId===l.id),status=!editing&&availability.whole.length?say('Salón reservado','Entire room reserved'):!tables.length?say('Sin mesas','No tables'):editing?`${tables.length} ${say('mesas','tables')}`:availability.full?say('Sin disponibilidad','Unavailable'):`${availability.available}/${tables.length} ${say('mesas libres','tables free')}`;
    const enter=()=>{onSelect(l.id);if(!editing)onOpen(l.id)};
    return <g key={l.id} data-area-label={l.id} className={`overviewAreaLabel ${!editing&&availability.full?'occupied':''}`} role="button" tabIndex={0} aria-label={`${l.name} · ${status}`} aria-pressed={l.id===areaId} onPointerDown={e=>beginDrag(e,l.id)} onClick={()=>{if(!editing)enter()}} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();enter()}}}>
     <title>{`${l.name} · ${status}`}</title><rect x={l.x} y={l.y} width={l.width} height={l.height} rx="10" fill="var(--fp-bg)" stroke={l.id===areaId?'#529f8e':'var(--fp-line)'} strokeWidth="2"/>
     {l.lines.map((line,i)=><text key={i} x={l.x+14} y={l.y+26+i*26} fontSize="22" fontWeight="750" fill="var(--fp-text)">{line}</text>)}
     <text x={l.x+14} y={l.y+l.height-12} fontSize="18" fill="var(--fp-muted)">{status}</text>
    </g>;
   })}
   {editing&&selected&&resizeArea===selected.id&&(()=>{const geometry=floorMapAreaGeometry(layout,selected),frame=geometry.frame,right=frame.x+frame.width,bottom=frame.y+frame.height;return <g><rect data-area-resize={selected.id} x={right-45} y={bottom-45} width="90" height="90" fill="transparent" className="overviewResizeTarget" role="button" tabIndex={0} aria-label={say(`Cambiar tamaño de ${selected.name}`,`Resize ${selected.name}`)} onPointerDown={e=>beginDrag(e,selected.id,true)} onKeyDown={e=>{if(busy||!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();update(selected.id,resizeFloorMapArea(geometry,frame.width+(e.key==='ArrowLeft'?-11:e.key==='ArrowRight'?11:0),frame.height+(e.key==='ArrowUp'?-7.6:e.key==='ArrowDown'?7.6:0)))}}/><rect x={right-12} y={bottom-12} width="24" height="24" rx="6" className="overviewResizeHandle" pointerEvents="none"/><path d={`M ${right-5} ${bottom+5} l 10 -10 m -5 10 l 5 -5`} stroke="white" strokeWidth="2" pointerEvents="none"/></g>})()}
   {!areas.length&&<text x="550" y="350" textAnchor="middle" fontSize="21" fill="var(--fp-muted)">{say('Este nivel aún no tiene áreas','No areas on this level yet')}</text>}
  </svg>);
 // Export reuses the exact map scene without mounting the agenda or changing the working view.
 if(exportLevelId)return drawing;
 return <section className="restaurantOverview" aria-label={say('Mapa completo del restaurante','Complete restaurant map')}>
  <div className="overviewLevelBar"><div role="group" aria-label={say('Niveles del restaurante','Restaurant levels')}>{levels.map(l=><button type="button" key={l.id} aria-pressed={activeLevel.id===l.id} onClick={()=>{setLevel(l.id);const first=layout.areas.find(a=>areaLevel(layout,a)===l.id);if(first)onSelect(first.id)}}><Layers size={15}/>{levelName(l.name,en)}<span>{layout.areas.filter(a=>areaLevel(layout,a)===l.id).length}</span></button>)}{editing&&<button type="button" disabled={busy||levels.length>=10} onClick={addLevel}><Plus size={16}/>{say('Agregar nivel','Add level')}</button>}</div></div>
  <div className="overviewMetrics"><span><b>{areas.length}</b>{say('áreas','areas')}</span><span><b>{totals.tables}</b>{say('mesas','tables')}</span><span><b>{totals.seats}</b>{say('lugares','seats')}</span>{!editing&&<span className="available"><b>{totals.free}</b>{say('mesas disponibles','available tables')}</span>}</div>
  {editing&&<div className="overviewLevelEditor"><label>{say('Nombre del nivel','Level name')}<input maxLength={40} value={levelName(activeLevel.name,en)} disabled={busy} onChange={e=>onChange({...layout,levels:levels.map(l=>l.id===activeLevel.id?{...l,name:e.target.value}:l)})}/></label>{levels.length>1&&!areas.length&&<button type="button" className="floorTextButton danger" disabled={busy} onClick={()=>{onChange({...layout,levels:levels.filter(l=>l.id!==activeLevel.id)});setLevel(levels.find(l=>l.id!==activeLevel.id)!.id)}}>{say('Quitar nivel vacío','Remove empty level')}</button>}<span><Move size={15}/>{say('Arrastre un área para moverla. Active Cambiar tamaño del área para ajustar su esquina.','Drag an area to move it. Enable Resize area to adjust its corner.')}</span></div>}
  <div className={`overviewWorkspace ${editing?'':'withReservations'} ${map.wide?'mapWide':''}`}><div className="overviewMapColumn"><div className="overviewMapTools"><b>{levelName(activeLevel.name,en)}</b><MapNavigation map={map} en={en}/></div>
  <div ref={map.viewport} {...map.bindings} style={{'--map-ratio':mapBounds.width/mapBounds.height,touchAction:'none'} as CSSProperties} className={`overviewCanvas mapViewport ${map.hand?'mapHandActive':''} ${map.panning?'mapPanning':''}`} tabIndex={0} aria-label={say('Vista desplazable del restaurante','Scrollable restaurant view')}>{drawing}</div>{!editing&&<div className="overviewMapHint overviewWorkHint"><span aria-live="polite">{detailTitle||say('Toque una mesa: su agenda se abre junto al mapa. Use dos dedos para acercar o recorrer el mapa; también puede usar +/−.','Tap a table: its schedule opens beside the map. Use two fingers to zoom or pan; +/− also works.')}</span>{detailPanel&&<button type="button" className="secondary" onClick={()=>sidebar.current?.scrollIntoView({block:'nearest',behavior:'smooth'})}>{say('Ver detalle','View details')}</button>}</div>}</div>
  {editing?<aside className="overviewAreaPanel"><h3>{say(editing?'Ubicar áreas':'Áreas de este nivel',editing?'Arrange areas':'Areas on this level')}</h3>
   {editing&&<><p>{say('Arrastre el área para moverla. Para redimensionarla, active Cambiar tamaño del área y arrastre la esquina marcada. Use dos dedos para acercar, alejar o recorrer el mapa.','Drag the area to move it. To resize it, enable Resize area and drag the marked corner. Use two fingers to zoom or pan the map.')}</p><label>{say('Seleccionar área','Select area')}<select aria-label={say('Seleccionar área','Select area')} disabled={busy} value={selected?.id||''} onChange={e=>{const a=layout.areas.find(a=>a.id===e.target.value);if(a){setLevel(areaLevel(layout,a));onSelect(a.id)}}}><option value="" disabled>{say('Seleccione…','Choose…')}</option>{layout.areas.map(a=><option key={a.id} value={a.id}>{a.name} · {levelName(levels.find(l=>l.id===areaLevel(layout,a))!.name,en)}</option>)}</select></label></>}
   {editing&&selected&&<><button type="button" className="overviewResizeMode" disabled={busy||map.hand} aria-pressed={resizeArea===selected.id} onClick={()=>setResizeArea(current=>current===selected.id?null:selected.id)}><ArrowUpRight size={17}/>{say('Cambiar tamaño del área','Resize area')}</button>{resizeArea===selected.id&&<p role="status">{say('Arrastre la esquina marcada. Al soltar, volverá al modo mover.','Drag the marked corner. Releasing returns to move mode.')}</p>}<label>{say('Nivel del área','Area level')}<select aria-label={say('Nivel del área','Area level')} value={activeLevel.id} disabled={busy} onChange={e=>{update(selected.id,{levelId:e.target.value});setLevel(e.target.value)}}>{levels.map(l=><option key={l.id} value={l.id}>{levelName(l.name,en)}</option>)}</select></label><label className="overviewAppearance"><input type="checkbox" checked={selected.background!=='solid'} disabled={busy} onChange={e=>onChange({...layout,areas:layout.areas.map(a=>a.id===selected.id?{...a,background:e.target.checked?'transparent':'solid'}:a)})}/>{say('Fondo transparente','Transparent background')}</label><label className="overviewAppearance"><input type="checkbox" checked={selected.showBorder!==false} disabled={busy} onChange={e=>onChange({...layout,areas:layout.areas.map(a=>a.id===selected.id?{...a,showBorder:e.target.checked}:a)})}/>{say('Mostrar contorno','Show border')}</label><button type="button" className="primary" disabled={busy} onClick={()=>onOpen(selected.id)}>{say('Editar mesas del área','Edit area tables')}<ArrowUpRight size={16}/></button></>}
   {!areas.length&&<p>{editing?say('Elija un área en el selector y cambie su nivel para traerla aquí.','Choose an area and change its level to move it here.'):say('Cambie de nivel para ver otras áreas.','Switch levels to see other areas.')}</p>}
  </aside>:<div ref={sidebar} className="overviewSidebar"><div hidden={!!detailPanel}><OverviewReservations key={date} {...reservationProps} bookings={bookings} layout={layout} date={date} en={en} onLocate={b=>{setFocused(b?.reservation.id||null);const a=layout.areas.find(a=>b?.areaIds.includes(a.id));if(a){setLevel(areaLevel(layout,a));onSelect(a.id)}}}/></div>{detailPanel&&<div className="overviewContext">{detailPanel}</div>}</div>}</div>
 </section>;
}
