const test=require('node:test'),assert=require('node:assert/strict'),ts=require('typescript'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
const restaurant='11111111-1111-4111-8111-111111111111',other='22222222-2222-4222-8222-222222222222',file='33333333-3333-4333-8333-333333333333';
const origin='https://fixture.supabase.co',png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jJ1sAAAAASUVORK5CYII=','base64'),data='data:image/png;base64,'+png.toString('base64');
function fixture(){
 const f={settings:{logo_data_url:data,private_note:'never expose'},published:true,calls:[],fetches:[],slug:'sample',error:null};
 const admin={from:table=>{const query={table,filters:[],columns:''};f.calls.push(query);const q={select:cols=>{query.columns=cols;return q},eq:(a,b)=>{query.filters.push([a,b]);return q},maybeSingle:async()=>({error:f.error,data:table==='v2_public_pages'?(f.published&&query.filters.some(([k,v])=>k==='slug'&&v===f.slug)?{restaurant_id:restaurant,content:{logo:restaurant+'/'+file+'.png'}}:null):{settings:f.settings}})};return q}};
 const modules={};function load(p){p=path.resolve(p);if(modules[p])return modules[p].exports;const m={exports:{}};modules[p]=m;vm.runInNewContext(ts.transpileModule(fs.readFileSync(p,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports:m.exports,module:m,require:n=>n==='@/lib/public-server'?{publicAdmin:()=>admin}:n==='@/lib/restaurant-public'?{validSlug:s=>/^[a-z0-9-]{3,64}$/.test(s)}:n.startsWith('@/')?load(n.slice(2)+'.ts'):require(n),URL,Buffer,Uint8Array,Response,AbortSignal,process:{env:{NEXT_PUBLIC_SUPABASE_URL:origin}},fetch:async(url,options)=>{f.fetches.push({url,options});return new Response(png)}});return m.exports;}
 f.helper=load('lib/public-logo.ts');const {GET}=load('app/r/[slug]/logo/route.ts');f.get=(slug='sample')=>GET(null,{params:Promise.resolve({slug})});return f;
}
test('publishes only the logo from its own General settings, never other settings',async()=>{const f=fixture(),r=await f.get();assert.equal(r.status,200);assert.equal(r.headers.get('content-type'),'image/png');assert.equal(r.headers.get('cache-control'),'no-store');assert.deepEqual(Buffer.from(await r.arrayBuffer()),png);assert(f.calls[1].filters.some(([k,v])=>k==='id'&&v===restaurant));assert.equal(f.fetches.length,0)});
test('unpublished or missing pages cannot expose restaurant branding',async()=>{for(const slug of ['sample','unknown','../bad']){const f=fixture();f.published=false;const r=await f.get(slug);assert.equal(r.status,404);assert(!f.calls.some(c=>c.table==='v2_restaurants'));assert.equal(f.fetches.length,0)}});
test('explicit logo removal suppresses the previous public logo',async()=>{const f=fixture();f.settings={logo_data_url:''};assert.equal((await f.get()).status,404);assert.equal(f.fetches.length,0);f.settings={};assert.equal((await f.get()).status,200);assert.equal(f.fetches[0].url,origin+'/storage/v1/object/public/unomesa-public/'+restaurant+'/'+file+'.png')});
test('remote logos only fetch the exact configured storage origin and tenant branding prefix',async()=>{for(const url of ['https://evil.test/a.png',origin+'/storage/v1/object/public/mrmaa-branding/'+other+'/logo.png',origin+'/storage/v1/object/public/private/'+restaurant+'/logo.png',origin+'/storage/v1/object/public/mrmaa-branding/'+restaurant+'/%2e%2e/private.png','data:image/svg+xml;base64,PHN2Zz4=']){const f=fixture();f.settings={logo_data_url:url};assert.equal((await f.get()).status,404);assert.equal(f.fetches.length,0)}const f=fixture();f.settings={logo_data_url:origin+'/storage/v1/object/public/mrmaa-branding/'+restaurant+'/logo-'+file+'.png'};assert.equal((await f.get()).status,200);assert.equal(f.fetches[0].options.redirect,'error')});
test('database errors and invalid image content fail closed without leaking diagnostics',async()=>{const f=fixture();f.error={message:'secret'};let r=await f.get();assert.equal(r.status,503);assert.equal(await r.text(),'');f.error=null;f.settings={logo_data_url:'data:image/png;base64,PHNjcmlwdD4='};r=await f.get();assert.equal(r.status,502);assert.equal(await r.text(),'')});
