import { LegalPage, LegalSection } from "@/components/legal-page";

export default function DataProcessingPage() {
  return <LegalPage updatedOn="2026-09-15" title="Acuerdo de tratamiento de datos" intro="Condiciones básicas bajo las cuales UnoMesa procesa datos por cuenta del restaurante contratante.">
    <LegalSection title="Objeto e instrucciones"><p>MYM S.A. procesará los datos personales cargados por el cliente únicamente para prestar UnoMesa, conforme al contrato, configuración del cliente e instrucciones documentadas lícitas.</p></LegalSection>
    <LegalSection title="Personas y datos"><p>El tratamiento puede comprender datos de clientes, prospectos, empleados y usuarios; datos identificativos, contacto, reservaciones, preferencias operativas, cotizaciones, horarios y registros de actividad. No deben cargarse datos sensibles innecesarios.</p></LegalSection>
    <LegalSection title="Confidencialidad y seguridad">
      <p>MYM S.A. tratará como confidenciales los datos personales y operativos del restaurante, mantendrá su separación respecto de otros negocios y limitará el acceso dentro de UnoMesa a los usuarios autorizados del restaurante según sus permisos. No venderá estos datos ni los utilizará para publicidad de terceros ni los pondrá a disposición de otros restaurantes. El cliente administrará roles, credenciales, archivos compartidos y legitimidad de la información.</p>
      <p>El personal autorizado de UnoMesa y sus proveedores técnicos podrán tratar esta información o acceder a ella únicamente cuando sea necesario para prestar el servicio, brindar soporte, mantener la seguridad o cumplir una obligación legal, limitando el acceso a lo necesario y bajo obligaciones de confidencialidad.</p>
      <p>Aplicaremos las medidas de protección descritas en la Política de privacidad para prevenir accesos no autorizados y filtraciones. Los incidentes confirmados se investigarán y comunicarán conforme a dicha política y la legislación aplicable.</p>
    </LegalSection>
    <LegalSection title="Subencargados"><p>El cliente autoriza el uso de proveedores necesarios de infraestructura, autenticación, comunicaciones y pagos. MYM S.A. mantendrá obligaciones apropiadas con dichos proveedores y comunicará cambios materiales cuando corresponda.</p></LegalSection>
    <LegalSection title="Asistencia"><p>UnoMesa brindará asistencia razonable para responder solicitudes de derechos, investigar incidentes y exportar o eliminar información, considerando la naturaleza del servicio y la información disponible.</p></LegalSection>
    <LegalSection title="Finalización"><p>Al terminar el servicio, el cliente podrá exportar información durante el plazo aplicable. Después, los datos se eliminarán o anonimizarán conforme a la política de retención, excepto cuando una obligación legal exija conservarlos.</p></LegalSection>
    <LegalSection title="Asistente de inteligencia artificial"><p>El asistente de ayuda utiliza OpenAI para responder preguntas sobre UnoMesa. Al enviar una consulta, se transmiten su mensaje, un historial breve de la conversación, el idioma, el plan y el rol, junto con fragmentos del tutorial. No consulta automáticamente registros de clientes, cotizaciones, reservaciones ni empleados. Evite incluir datos personales, contraseñas o códigos. UnoMesa guarda el contador de uso y respuestas para evitar solicitudes duplicadas; no guarda el texto de las preguntas en este registro. El proveedor puede conservar datos conforme a sus políticas de seguridad y retención. Las respuestas pueden contener errores.</p></LegalSection>
  </LegalPage>;
}
