import { LegalPage, LegalSection } from "@/components/legal-page";

export default function TermsPage() {
  return <LegalPage title="Términos y condiciones" intro="Condiciones aplicables al acceso y uso profesional de MRMAA por restaurantes y sus usuarios autorizados.">
    <LegalSection title="1. Proveedor y aceptación"><p>MRMAA es una plataforma operada por MYM S.A. Al crear, activar o utilizar una cuenta, el negocio contratante y sus usuarios autorizados aceptan estos términos, la Política de Privacidad y las condiciones del plan contratado. Quien acepta en nombre de un negocio declara tener autoridad suficiente.</p></LegalSection>
    <LegalSection title="2. Servicio"><p>MRMAA facilita la administración de reservaciones, clientes, cotizaciones, anticipos registrados, empleados, horarios, reportes y configuraciones. No constituye asesoría legal, contable, fiscal o laboral, ni sustituye un sistema oficial de facturación o procesamiento bancario.</p></LegalSection>
    <LegalSection title="3. Cuentas y roles"><p>El administrador principal controla invitaciones y permisos. Las credenciales son personales. El negocio debe mantener actualizados sus usuarios, desactivar accesos innecesarios y proteger sus dispositivos. El negocio responde por las acciones realizadas mediante sus cuentas, salvo fallas atribuibles directamente a MRMAA.</p></LegalSection>
    <LegalSection title="4. Datos del cliente"><p>El negocio conserva la titularidad de la información que incorpora. Autoriza a MYM S.A. y a sus proveedores técnicos a alojarla y procesarla únicamente para operar, asegurar, respaldar y mejorar el servicio. El negocio garantiza que puede tratar legítimamente los datos de sus clientes y empleados.</p></LegalSection>
    <LegalSection title="5. Prueba, pagos y renovación"><p>La duración de la prueba, precio, moneda, impuestos, periodicidad y fecha de renovación se mostrarán antes de contratar. Una suscripción recurrente solo se cobrará con autorización expresa. Salvo indicación distinta, la cancelación evita renovaciones futuras y el servicio continúa hasta finalizar el período pagado.</p></LegalSection>
    <LegalSection title="6. Mora y acceso restringido"><p>Ante falta de pago podrá aplicarse un período de gracia. Después, la cuenta podrá pasar a modo de solo lectura para permitir la consulta y exportación durante el plazo informado. Vencido ese plazo, el acceso podrá suspenderse, sin perjuicio de las obligaciones legales de conservación.</p></LegalSection>
    <LegalSection title="7. Uso permitido"><p>No se permite vulnerar controles, acceder a otros negocios, introducir código malicioso, realizar cargas automatizadas abusivas, usar datos obtenidos ilegalmente, revender el servicio sin autorización o emplearlo para actividades ilícitas. MRMAA podrá limitar o suspender accesos ante un riesgo razonable.</p></LegalSection>
    <LegalSection title="8. Disponibilidad y terceros"><p>MRMAA procurará una disponibilidad razonable, pero no garantiza operación ininterrumpida. Puede depender de Supabase, Vercel, proveedores de correo, pagos y comunicaciones. Podrán realizarse mantenimientos y medidas de emergencia para proteger el sistema.</p></LegalSection>
    <LegalSection title="9. Verificación de información"><p>El negocio debe revisar fechas, horarios, áreas, precios, impuestos, descuentos, propinas, anticipos, saldos y documentos antes de utilizarlos o enviarlos. MRMAA no garantiza que la información introducida por el usuario sea correcta.</p></LegalSection>
    <LegalSection title="10. Propiedad intelectual"><p>MYM S.A. conserva los derechos sobre MRMAA, su código, diseño, documentación y marcas. La suscripción concede un derecho limitado, revocable, no exclusivo y no transferible de uso interno durante la vigencia del servicio.</p></LegalSection>
    <LegalSection title="11. Responsabilidad"><p>En la máxima medida permitida por la ley, MRMAA no responderá por daños indirectos, lucro cesante o decisiones tomadas con información no verificada. La responsabilidad acumulada de MYM S.A. se limitará a lo pagado por el cliente durante los doce meses anteriores al hecho, excepto cuando la ley prohíba esa limitación.</p></LegalSection>
    <LegalSection title="12. Terminación y exportación"><p>El cliente puede cancelar conforme a su plan. La eliminación completa de un negocio requerirá confirmación del administrador. Los registros podrán conservarse temporalmente en papelera o respaldos técnicos conforme a la Política de Privacidad; un respaldo técnico no garantiza restauración individual.</p></LegalSection>
    <LegalSection title="13. Cambios y legislación"><p>Los cambios materiales se notificarán razonablemente y podrán requerir nueva aceptación. Estos términos se rigen principalmente por las leyes de Guatemala. Las normas obligatorias aplicables de México o Estados Unidos prevalecerán para clientes ubicados allí. Las partes procurarán una solución de buena fe antes de acudir a la autoridad competente.</p></LegalSection>
  </LegalPage>;
}
