export type ReservationReportMode='both'|'reservations'|'summary';
export type ReservationReport={restaurant:string;title:string;context:string;generated:string;mode:ReservationReportMode;language:string;metrics:{label:string;value:string}[];columns:{label:string;weight:number}[];rows:string[][]};
const escape=(value:string)=>value.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));

/** Both output formats consume the same complete, filtered report. */
export function reservationReportHtml(report:ReservationReport){
 const metrics=report.mode==='reservations'?'':`<section class="metrics">${report.metrics.map(m=>`<div><strong>${escape(m.value)}</strong><span>${escape(m.label)}</span></div>`).join('')}</section>`;
 const table=report.mode==='summary'?'':`<table><colgroup>${report.columns.map(c=>`<col style="width:${c.weight/report.columns.reduce((s,v)=>s+v.weight,0)*100}%">`).join('')}</colgroup><thead><tr>${report.columns.map(c=>`<th>${escape(c.label)}</th>`).join('')}</tr></thead><tbody>${report.rows.map(row=>`<tr>${row.map(cell=>`<td>${escape(cell)}</td>`).join('')}</tr>`).join('')}</tbody></table>`;
 return `<!doctype html><html lang="${report.language==='en'?'en':'es'}"><head><meta charset="utf-8"><title>${escape(report.title)}</title><style>@page{size:A4 landscape;margin:12mm}body{font:10pt Arial,sans-serif;color:#18181b;margin:0}h1{font-size:19pt;margin:0 0 6px}h2{font-size:12pt;margin:0 0 8px}p{font-size:9pt;margin:4px 0;overflow-wrap:anywhere}.generated{color:#666}.metrics{display:flex;gap:12px;margin:18px 0}.metrics>div{border:1px solid #ddd;border-radius:8px;padding:12px 18px;min-width:90px}.metrics strong,.metrics span{display:block}.metrics strong{font-size:16pt}.metrics span{font-size:9pt;margin-top:4px;color:#555}table{width:100%;border-collapse:collapse;table-layout:fixed;margin-top:14px}thead{display:table-header-group}th,td{text-align:left;vertical-align:top;padding:7px 5px;border-bottom:1px solid #ddd;font-size:8.5pt;white-space:pre-wrap;overflow-wrap:anywhere}th{background:#18181b;color:#fff;-webkit-print-color-adjust:exact;print-color-adjust:exact}tbody tr:nth-child(even){background:#f7f7f8}</style></head><body><h1>${escape(report.restaurant)}</h1><h2>${escape(report.title)}</h2><p>${escape(report.context)}</p><p class="generated">${escape(report.generated)}</p>${metrics}${table}</body></html>`;
}
