import {tableBookingDescription,type TableBookingLine} from '@/lib/floor-table-schedule';
import {floorTableName} from '@/lib/floor-table-label';
import {floorTableScale,type FloorTable} from '@/lib/floor-plan';
export function FloorTableGraphic({table:t,state,selected=false,editing=false,en=false,labelAspect=1,labelUnit=1,compact=false,allBookings=false,bookings=[]}:{table:FloorTable;state:string;selected?:boolean;editing?:boolean;en?:boolean;labelAspect?:number;labelUnit?:number;compact?:boolean;allBookings?:boolean;bookings?:TableBookingLine[]}){
 const reserved=state==='reserved'&&!editing;
 // Keep booked tables visibly blue even while selected; the gold outline marks the selection.
 const palette=reserved?['#2456c7','#ffffff','#173b91']:selected?['#efe1d2','#704a2d','#bc9571']:state==='free'?['#e1f0e8','#286a50','#9bbdab']:state==='seated'?['#fff0db','#9b601b','#dfb978']:['#ffe8e7','#a43535','#d99a95'];
 const outline=reserved&&selected?'#e9ad55':palette[2],outlineWidth=selected?4:reserved?3:2;
 const w=t.shape==='rectangle'?142:100,h=t.shape==='rectangle'?80:100,scale=floorTableScale(t);
 const label=selected?(en?'Selected':'Seleccionada'):editing?'':({free:en?'Available':'Disponible',reserved:en?'Reserved':'Reservada',seated:en?'Seated':'En mesa',review:en?'Review':'Revisar'}[state]||state);
 const name=floorTableName(t.name,en),max=scale<.7?6:10,nameSize=compact?Math.min(14,42*scale*labelUnit)/labelUnit:Math.max(12,20*scale);
 const lines=editing?[]:bookings,rows=allBookings?lines:lines.slice(0,2),rowStep=Math.min(17,allBookings?32/Math.max(1,rows.length-1):17),rowSize=Math.min(compact?15:12,rowStep*.8)*scale,heading=lines.length?18*scale:nameSize;
 return <><title>{tableBookingDescription(lines,en)}</title><g transform={`scale(${scale}) rotate(${t.rotation})`}>
  {Array.from({length:Math.min(t.seats,8)},(_,i)=>{const count=Math.min(t.seats,8),angle=i/count*Math.PI*2,cx=Math.sin(angle)*(w/2+12),cy=Math.cos(angle)*(h/2+12);return <rect key={i} x={cx-12} y={cy-6} width="24" height="12" rx="4" fill={palette[2]} transform={`rotate(${-angle*180/Math.PI} ${cx} ${cy})`}/>})}
  {t.shape==='round'?<circle r="50" fill={palette[0]} stroke={outline} strokeWidth={outlineWidth}/>:<rect x={-w/2} y={-h/2} width={w} height={h} rx={t.shape==='rectangle'?15:18} fill={palette[0]} stroke={outline} strokeWidth={outlineWidth}/>}
 </g><g transform={`scale(${Math.min(1,1/labelAspect)} ${Math.min(1,labelAspect)})`}><text textAnchor="middle" y={lines.length?-22*scale:compact?nameSize*.35:-4*scale} fill={palette[1]} fontSize={heading} fontWeight="700" pointerEvents="none">{name.length>max?name.slice(0,max-1)+'…':name}</text>{lines.length>0&&<g data-all-bookings={allBookings?'true':undefined} className="floorTableSchedule" pointerEvents="none" fill={palette[1]} textAnchor="middle" fontSize={rowSize} fontWeight="600">{rows.map((line,i)=>{const text=`${line.guests}p${lines.length>1&&line.extraSeats?`+${line.extraSeats}${line.group?'g':en?'s':'as.'}`:''} · ${line.time.replace(/ /g,'')}${line.continued?' ↶':''}`,width=(t.rotation===90?h:w)*.86*scale;return <text data-booking-id={line.id} key={line.id} y={(-3+i*rowStep)*scale} textLength={text.length*rowSize*.6>width?width:undefined} lengthAdjust="spacingAndGlyphs">{text}</text>})}<text y={32*scale} fontSize={11*scale}>{!allBookings&&lines.length>2?`+${lines.length-2} ${en?'more':'más'}`:lines.length===1&&lines.some(l=>l.extraSeats)?`+${Math.max(...lines.map(l=>l.extraSeats))} ${lines.some(l=>l.group)?(en?'group seats':'grupo'):(en?'seats':'asientos')}`:''}</text></g>}{!compact&&!lines.length&&<><text textAnchor="middle" y={20*scale} fill={palette[1]} fontSize={Math.max(10,14*scale)} pointerEvents="none">{t.seats}{scale>=.7?' '+(en?'seats':'lugares'):''}</text><text textAnchor="middle" y={((t.rotation===90?w:h)/2+44)*scale} fill="currentColor" fontSize={Math.max(10,13*scale)} pointerEvents="none">{label}</text></>}</g></>;
}
