import { LegalPage, LegalSection } from "@/components/legal-page";

export default function PrivacyPage() {
  return <LegalPage updatedOn="2026-09-15" title="Política de privacidad" intro="Cómo MYM S.A. recopila, utiliza, protege y conserva información al prestar UnoMesa.">
    <LegalSection title="1. Información tratada"><p>Podemos tratar datos de cuenta, contacto, restaurante, suscripción, soporte, seguridad y uso. Por cuenta del restaurante alojamos datos que este registra sobre clientes, reservaciones, cotizaciones, empleados y horarios.</p></LegalSection>
    <LegalSection title="2. Finalidades"><p>Utilizamos la información para autenticar usuarios, prestar funciones, enviar comunicaciones necesarias, prevenir fraude, mantener auditorías, brindar soporte, cumplir obligaciones legales y mejorar seguridad y rendimiento.</p></LegalSection>
    <LegalSection title="3. Roles de privacidad"><p>El restaurante determina los fines de los datos de sus clientes y empleados y actúa como responsable. MYM S.A. los procesa como proveedor conforme a instrucciones del restaurante, salvo datos propios de cuenta, facturación, seguridad y cumplimiento.</p></LegalSection>
    <LegalSection title="3.1. Confidencialidad de los datos del restaurante">
      <p>Los datos personales y operativos que registra cada restaurante, incluidos clientes, empleados, reservaciones, cotizaciones, precios, anticipos, horarios y reportes, se tratan como información confidencial. UnoMesa mantiene esta información separada por negocio. Dentro de la aplicación, su acceso se limita a usuarios autorizados del restaurante, conforme a sus roles y permisos.</p>
      <p>UnoMesa no vende los datos personales u operativos del restaurante ni los utiliza para publicidad de terceros. Tampoco los pone a disposición de otros restaurantes. El restaurante controla los documentos y archivos que sus usuarios decidan exportar, imprimir o compartir.</p>
      <p>El personal autorizado de UnoMesa y sus proveedores técnicos podrán tratar esta información o acceder a ella únicamente cuando sea necesario para prestar el servicio, brindar soporte, mantener la seguridad o cumplir una obligación legal, limitando el acceso a lo necesario y bajo obligaciones de confidencialidad.</p>
    </LegalSection>
    <LegalSection title="4. Proveedores y transferencias"><p>Podemos utilizar proveedores de infraestructura, autenticación, alojamiento, correo, analítica y pagos, incluidos servicios ubicados fuera del país del usuario. Exigiremos medidas contractuales y técnicas apropiadas según el servicio y jurisdicción.</p></LegalSection>
    <LegalSection title="5. Conservación"><p>Conservamos información mientras la cuenta esté activa y por períodos razonables posteriores para seguridad, respaldo, disputas y obligaciones legales. La papelera de la aplicación puede conservar registros hasta 365 días. Los respaldos técnicos siguen ciclos separados y no funcionan como archivo individual permanente.</p></LegalSection>
    <LegalSection title="6. Seguridad"><p>Aplicamos controles de acceso, autenticación, separación por negocio, cifrado proporcionado por la infraestructura, registro de actividad y respaldos para prevenir accesos no autorizados, divulgación, pérdida o alteración de información. Ningún sistema puede garantizar la ausencia absoluta de filtraciones o incidentes. El cliente debe usar contraseñas únicas, MFA cuando esté disponible y dispositivos protegidos.</p></LegalSection>
    <LegalSection title="7. Derechos y solicitudes"><p>Según la jurisdicción, una persona puede solicitar acceso, corrección, eliminación, oposición o portabilidad. Las solicitudes relativas a datos cargados por un restaurante deben dirigirse primero al restaurante. También puede escribir a support@unomesa.com.</p></LegalSection>
    <LegalSection title="8. Incidentes"><p>Investigaremos incidentes confirmados y notificaremos al cliente afectado y, cuando corresponda, a autoridades o personas dentro de los plazos exigidos por la legislación aplicable.</p></LegalSection>
    <LegalSection title="9. Menores"><p>UnoMesa es un servicio empresarial y no está dirigido a menores de edad. El cliente no debe cargar datos de menores salvo que cuente con una base legal y sean necesarios para su operación legítima.</p></LegalSection>
    <LegalSection title="Asistente de inteligencia artificial"><p>El asistente de ayuda utiliza OpenAI para responder preguntas sobre UnoMesa. Al enviar una consulta, se transmiten su mensaje, un historial breve de la conversación, el idioma, el plan y el rol, junto con fragmentos del tutorial. No consulta automáticamente registros de clientes, cotizaciones, reservaciones ni empleados. Evite incluir datos personales, contraseñas o códigos. UnoMesa guarda el contador de uso y respuestas para evitar solicitudes duplicadas; no guarda el texto de las preguntas en este registro. El proveedor puede conservar datos conforme a sus políticas de seguridad y retención. Las respuestas pueden contener errores.</p></LegalSection>
  </LegalPage>;
}
