import { BrandLogo } from "./brand-logo";
import { PLANS, PUBLIC_SIGNUP_ENABLED } from "@/lib/plans";
import { PublicMarketingAnalytics } from "./public-marketing-analytics";
import { EVENT_PATHS, eventPageStructuredData } from "@/lib/event-page-seo";
import type { PublicLanguage } from "@/lib/public-seo";
import s from "./event-management-page.module.css";

export function EventManagementPage({ language }: { language: PublicLanguage }) {
  const en = language === "en", t = (es: string, english: string) => en ? english : es;
  const home = en ? "/" : "/es", structured = eventPageStructuredData(language);
  const accountUrl = home + (PUBLIC_SIGNUP_ENABLED ? "?signup=1" : "?login=1");
  const cta = (es: string, english: string) => PUBLIC_SIGNUP_ENABLED ? t(es, english) : t("Iniciar sesión", "Sign in");
  const steps = [
    [t("Reciba la solicitud", "Receive the request"), t("Publique la página de su restaurante con menús y salones. Sus clientes envían los detalles de su evento a un buzón para que su equipo revise la solicitud y prepare la propuesta.", "Publish your restaurant page with menus and spaces. Guests send their event details to an inbox where your team can review the request and prepare a proposal.")],
    [t("Prepare una cotización clara", "Prepare a clear quote"), t("Reúna fecha, horario, número de invitados y área. Agregue menús, productos y servicios, revise cantidades y precios, aplique descuentos o propina y descargue un PDF con la imagen de su restaurante.", "Keep the date, time, guest count and area together. Add menus, products and services, check quantities and prices, apply discounts or tips and download a PDF with your restaurant’s branding.")],
    [t("Dé seguimiento y confirme", "Follow up and confirm"), t("Consulte los avisos de cotizaciones cuando se acerca la fecha del evento. Cuando el cliente acepte, convierta la propuesta en reserva y conserve sus detalles. Registre el anticipo recibido y consulte el saldo pendiente.", "Check quote reminders as the event date approaches. When the customer accepts, convert the proposal to a reservation and retain its details. Record the deposit received and review the remaining balance.")],
    [t("Organice el salón y el servicio", "Plan the room and service"), t("Asigne mesas o un salón completo desde el plano. Revise la agenda y los avisos de coincidencia de área y horario. Los planes Intermediate y Advanced incluyen horarios del personal; Advanced añade reportes para revisar cotizaciones, anticipos y resultados.", "Assign tables or an entire room from the floor plan. Check the schedule and area and time overlap alerts. Intermediate and Advanced include staff schedules; Advanced adds reports for reviewing quotes, deposits and results.")],
  ];
  return <main className={s.page} lang={language} translate="no">
    <PublicMarketingAnalytics />
    {structured && <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(structured).replace(/</g, "\\u003c") }} />}
    <nav className={s.nav} aria-label={t("Navegación principal", "Main navigation")}>
      <a href={home} aria-label={t("UnoMesa, inicio", "UnoMesa home")}><BrandLogo inverse /></a>
      <div><a href={home + "#planes"}>{t("Planes", "Plans")}</a><a href={EVENT_PATHS[en ? "es" : "en"]} hrefLang={en ? "es" : "en"}>{en ? "Español" : "English"}</a><a href={accountUrl} className={s.primary}>{cta("Pruebe gratis", "Try it free")}</a></div>
    </nav>
    <header className={s.hero}>
      <p className={s.eyebrow}>{t("Para restaurantes con eventos y grupos grandes", "For restaurants that host events and large groups")}</p>
      <h1>{t("Software para gestionar eventos en su restaurante.", "Restaurant event management, from quote to reservation.")}</h1>
      <p className={s.intro}>{t("Una cena de empresa o una celebración de grupo reúne muchos detalles: menú, invitados, salón, fecha y anticipo. UnoMesa conecta la cotización con la reserva para que su equipo trabaje con la misma información.", "A company dinner or group celebration brings many details together: menu, guests, room, date and deposit. UnoMesa connects the quote to the reservation so your team can work from the same information.")}</p>
      <div className={s.actions}><a className={s.primary} href={accountUrl}>{cta("Pruebe Advanced gratis 10 días", "Try Advanced free for 10 days")}</a><a href={home}>{t("Explore la demo sin registro →", "Explore the demo without signup →")}</a></div>
      <p className={s.note}>{t(`Sin tarjeta. Después, planes desde US$${PLANS[0].monthly}/mes por restaurante.`, `No card required. Then, plans from US$${PLANS[0].monthly}/month per restaurant.`)}</p>
    </header>
    <section className={s.section} aria-labelledby="event-workflow"><p className={s.eyebrow}>{t("El recorrido de un evento", "The event workflow")}</p><h2 id="event-workflow">{t("De la solicitud al servicio, paso a paso.", "From inquiry to service, step by step.")}</h2><ol className={s.grid}>{steps.map(([title, body], i) => <li key={title}><span className={s.number}>0{i + 1}</span><h3>{title}</h3><p>{body}</p></li>)}</ol></section>
    <section className={s.example} aria-labelledby="event-example"><div><p className={s.eyebrow}>{t("Ejemplo de uso · Datos ficticios", "Example workflow · Sample data")}</p><h2 id="event-example">{t("Una cena de empresa para 40 invitados.", "A company dinner for 40 guests.")}</h2></div><p>{t("Prepare la propuesta del menú para 40 personas, seleccione el salón y guarde la fecha y el horario. Cuando se apruebe, convierta la cotización en reserva y registre el anticipo recibido. Antes del evento, su equipo podrá consultar la misma información para preparar el servicio.", "Prepare the menu proposal for 40 guests, select the room and save the date and time. Once approved, convert the quote to a reservation and record the deposit received. Before the event, your team can consult the same information to prepare the service.")}</p></section>
    <section className={s.section} aria-labelledby="event-faq"><h2 id="event-faq">{t("Reservas diarias y eventos, en el mismo sistema.", "Daily reservations and events, in the same system.")}</h2>
      <details><summary>{t("¿Puedo crear reservas sin cotización?", "Can I create reservations without a quote?")}</summary><p>{t("Sí. Cree una reserva directamente cuando no necesite preparar una propuesta. Use las cotizaciones para grupos que requieren definir menús, servicios y condiciones antes de confirmar.", "Yes. Create a reservation directly when a proposal is not needed. Use quotes for groups that need menus, services and terms agreed before confirmation.")}</p></details>
      <details><summary>{t("¿Las solicitudes públicas confirman una reserva?", "Do public requests confirm a booking?")}</summary><p>{t("No. Llegan al buzón para revisión de su equipo. Usted comprueba la disponibilidad y prepara la cotización. UnoMesa permite registrar los anticipos recibidos; el formulario público no cobra pagos a sus clientes.", "No. They arrive in your team’s inbox for review. You check availability and prepare the quote. UnoMesa lets you record deposits received; the public form does not collect payments from your guests.")}</p></details>
      <details><summary>{t("¿El sistema envía los recordatorios al cliente?", "Does the system send reminders to the customer?")}</summary><p>{t("Los avisos aparecen dentro de UnoMesa para que su equipo haga el seguimiento. No sustituyen el contacto con el cliente ni envían automáticamente la cotización.", "Reminders appear inside UnoMesa so your team can follow up. They do not replace contact with the customer or automatically send the quote.")}</p></details>
      <details><summary>{t("¿Qué puedo probar antes de pagar?", "What can I try before paying?")}</summary><p>{t("Puede explorar la demo de la página principal sin registrarse. Al crear una cuenta nueva recibe 10 días de Advanced sin tarjeta, con tutorial dentro de la aplicación. Al terminar la prueba necesita una suscripción para continuar operando.", "Explore the demo on the home page without signing up. New accounts receive 10 days of Advanced with no card required and an in-app tutorial. A subscription is required to keep working after the trial ends.")}</p></details>
    </section>
    <footer className={s.footer}><h2>{t("Pruebe con la próxima propuesta de su restaurante.", "Try it with your restaurant’s next proposal.")}</h2><a className={s.primary} href={accountUrl}>{cta("Crear mi cuenta de prueba", "Create my trial account")}</a><p><a href={home}>{t("Software de reservaciones para restaurantes", "Restaurant reservation software")}</a> · <a href="/privacidad">{t("Privacidad", "Privacy")}</a> · <a href="/terminos">{t("Términos", "Terms")}</a></p></footer>
  </main>;
}
