export type Client = {
  id: string;
  restaurant_id: string;
  name: string;
  phone: string | null;
  email: string | null;
  notes: string | null;
};
export type QuoteItem = {
  id?: string;
  name: string;
  description: string;
  quantity: number;
  unit_price: number;
};
export type Quote = {
  id: string;
  restaurant_id: string;
  client_id: string | null;
  quote_number: number;
  client_name: string;
  client_phone: string;
  client_email: string;
  event_date: string;
  event_time: string;
  area: string;
  guests: number;
  discount_pct: number;
  tip_pct: number;
  subtotal: number;
  total: number;
  deposit: number;
  payment_method: string;
  balance: number;
  customer_note: string;
  internal_notes: string;
  status: string;
  created_at?: string;
  items: QuoteItem[];
};
export type Reservation = {
  id: string;
  restaurant_id: string;
  quote_id: string | null;
  client_id: string | null;
  client_name: string;
  phone: string;
  event_date: string;
  event_time: string;
  area: string;
  guests: number;
  menu: string;
  subtotal: number;
  discount_pct: number;
  tip_pct: number;
  total: number;
  deposit: number;
  payment_method: string;
  balance: number;
  notes: string;
  status: string;
};
