'use client';
import { useEffect,useRef,useState } from 'react';
import { PublicCatalogPicker } from './public-catalog-picker';
import { addPublicCatalogCards } from '@/lib/public-catalog';
import { openPublicContact, whatsappNumber } from '@/lib/public-contact';
import {PublicPageQr} from './public-page-qr';
import { supabase } from '@/lib/supabase';
import { cleanContent,emptyPublicContent,slugFor,validSlug,contactLink,assetUrl,publicPdfUrl,publicProblem,type PublicContent,type PublicCard,type Channel } from '@/lib/restaurant-public';
import { useAppPreferences } from './app-preferences';
import { useUnsavedChanges } from '@/lib/unsaved-changes';
import { RestaurantPublicPage } from './restaurant-public-page';
import s from './restaurant-public.module.css';
export function PublicPageSettings({restaurantId,restaurantName}:{restaurantId:string;restaurantName:string}){
 const {language}=useAppPreferences(),en=language==='en',t=(es:string,eng:string)=>en?eng:es;
 const [content,setContent]=useState<PublicContent>(emptyPublicContent(restaurantName)),[slug,setSlug]=useState(slugFor(restaurantName)),[published,setPublished]=useState(false),[revision,setRevision]=useState(0),[step,setStep]=useState(0),[assets,setAssets]=useState<any[]>([]),[products,setProducts]=useState<any[]>([]),[areas,setAreas]=useState<any[]>([]),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[baseline,setBaseline]=useState(''),[savedSlug,setSavedSlug]=useState(''),[savedPublished,setSavedPublished]=useState(false),[contactNotice,setContactNotice]=useState('');
 const lock=useRef(false);const snapshot=JSON.stringify({content,slug,published});useUnsavedChanges(loaded&&baseline!==snapshot,()=>{setBaseline(snapshot)});
 const set=<K extends keyof PublicContent>(key:K,value:PublicContent[K])=>setContent(c=>({...c,[key]:value}));
 async function load(){setBusy(true);setError('');try{const r=await supabase.rpc('v2_public_settings',{p_restaurant:restaurantId});if(r.error)throw r.error;const p=r.data?.page;let c=p?cleanContent(p.content):emptyPublicContent(restaurantName);if(!p){const restaurant=await supabase.from('v2_restaurants').select('name,phone,currency,language,settings').eq('id',restaurantId).single();if(restaurant.data){const x=restaurant.data;c={...c,name:x.name||restaurantName,currency:x.currency||'USD',language:x.language==='en'?'en':'es',address:x.settings?.business_address||'',email:x.settings?.business_email||'',phone:x.phone||''};}}
 setContent(c);setSlug(p?.slug||slugFor(restaurantName));setRevision(p?.revision||0);setPublished(!!p?.published);setSavedPublished(!!p?.published);setSavedSlug(p?.slug||'');setAssets(r.data.assets||[]);setBaseline(JSON.stringify({content:c,slug:p?.slug||slugFor(restaurantName),published:!!p?.published}));setLoaded(true);
 const catalogs=await Promise.all([supabase.from('v2_quote_products').select('id,name,description,price').eq('restaurant_id',restaurantId).eq('active',true).order('name').limit(200),supabase.from('v2_reservation_areas').select('id,name').eq('restaurant_id',restaurantId).eq('active',true).order('name').limit(200)]);setProducts(catalogs[0].data||[]);setAreas(catalogs[1].data||[]);
 }catch(e){setError(publicProblem(e,en));}finally{setBusy(false);}}
 useEffect(()=>{void load()},[restaurantId]);
 async function save(){if(lock.current)return;lock.current=true;setBusy(true);setError('');setNotice('');try{const c=cleanContent(content);if(!validSlug(slug))throw new Error('PUBLIC_INPUT');const r=await supabase.rpc('v2_public_save',{p_restaurant:restaurantId,p_slug:slug,p_content:c,p_published:published,p_revision:revision});if(r.error)throw r.error;setContent(c);setRevision(r.data.revision);setSavedSlug(r.data.slug);setSavedPublished(r.data.published);setBaseline(JSON.stringify({content:c,slug,published}));setNotice(t('Cambios guardados.','Changes saved.'));}catch(e){setError(publicProblem(e,en));}finally{lock.current=false;setBusy(false);}}
 async function upload(file:File|undefined,onDone:(path:string)=>void){if(!file||lock.current)return;setError('');if(file.size>3*1024*1024){setError(t('Máximo 3 MB por archivo. Comprima el PDF o imagen antes de subirlo.','Maximum 3 MB per file. Compress the PDF or image before uploading.'));return;}lock.current=true;setBusy(true);try{const session=await supabase.auth.getSession();const r=await fetch(`/api/public-assets?restaurant=${restaurantId}&name=${encodeURIComponent(file.name)}`,{method:'POST',headers:{Authorization:`Bearer ${session.data.session?.access_token}`,'Content-Type':file.type},body:file});const j=await r.json();if(!r.ok)throw new Error(j.error);setAssets(a=>[j,...a]);onDone(j.path);}catch(e){setError(publicProblem(e,en));}finally{lock.current=false;setBusy(false);}}
 async function removeAsset(a:any){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{const session=await supabase.auth.getSession();const r=await fetch(`/api/public-assets?restaurant=${restaurantId}&id=${a.id}`,{method:'DELETE',headers:{Authorization:`Bearer ${session.data.session?.access_token}`}});if(!r.ok)throw new Error('used');setAssets(xs=>xs.filter(x=>x.id!==a.id));}catch{setError(t('Quite primero el archivo del contenido y guarde. Si sigue fallando, vuelva a intentar.','Remove the file from the page and save first. If it still fails, retry.'));}finally{lock.current=false;setBusy(false);}}
 const addCard=(kind:'menus'|'areas',source?:any)=>{if(content[kind].length>=60)return;const card:PublicCard={id:crypto.randomUUID(),source_id:source?.id||'',name:source?.name||'',description:source?.description||'',price:source?.price!=null?String(source.price):'',category:kind==='menus'?t('Menús de eventos','Event menus'):'',image:'',capacity:''};set(kind,[...content[kind],card]);};
 function selectSources(kind:'menus'|'areas',ids:string[],checked:boolean){const chosen=new Set(ids);setContent(c=>({...c,[kind]:checked?addPublicCatalogCards(c[kind],(kind==='menus'?products:areas).filter(x=>chosen.has(x.id)),kind,t('Menús de eventos','Event menus')):c[kind].filter(card=>!card.source_id||!chosen.has(card.source_id))}));}
 const whatsappURL=contactLink('whatsapp',content,t('Prueba de contacto desde UnoMesa','UnoMesa contact test'));
 function testWhatsApp(){setContactNotice('');if(!whatsappURL){setContactNotice(t('Revise el número completo con código de país: +502 para Guatemala, +1 para EE. UU. o +52 para México. También puede pegar un enlace wa.me.','Check the full number with country code: +502 for Guatemala, +1 for the US or +52 for Mexico. You can also paste a wa.me link.'));return;}try{setContactNotice(openPublicContact(whatsappURL)?t('Se solicitó abrir WhatsApp. El mensaje no se envía automáticamente.','WhatsApp was requested. The message is not sent automatically.'):t('El navegador bloqueó la ventana. Use Abrir enlace o Copiar enlace.','Your browser blocked the window. Use Open link or Copy link.'));}catch{setContactNotice(t('No se pudo abrir. Use Abrir enlace o Copiar enlace.','Could not open. Use Open link or Copy link.'));}}
 const updateCard=(kind:'menus'|'areas',i:number,key:keyof PublicCard,value:string)=>setContent(c=>({...c,[kind]:c[kind].map((x,n)=>n===i?{...x,[key]:value}:x)}));
 function imageInput(title:string,path:string,onChange:(path:string)=>void){return <label>{title}<input disabled={busy} type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{void upload(e.target.files?.[0],onChange);e.target.value=''}}/>{path&&<div className={s.row}><img src={assetUrl(path)} alt="" width={70} height={55} style={{objectFit:'cover',borderRadius:10}}/><button type="button" onClick={()=>onChange('')}>{t('Quitar','Remove')}</button></div>}</label>}
 const cardEditor=(kind:'menus'|'areas')=><><div className={s.row}><h3>{kind==='menus'?t('Menús y carta digital','Menus and digital menu'):t('Salones','Spaces')}</h3><button type="button" disabled={busy||content[kind].length>=60} onClick={()=>addCard(kind)}>{t('Agregar manualmente','Add manually')}</button></div><PublicCatalogPicker kind={kind} rows={kind==='menus'?products:areas} selected={content[kind]} en={en} onSelect={(ids,checked)=>selectSources(kind,ids,checked)}/><p className={s.muted}>{t('Abra un elemento seleccionado para personalizar su información pública.','Open a selected item to customize its public details.')}</p>{content[kind].map((card,i)=><details className={s.editor} key={card.id} open={!card.name}><summary>{card.name||t('Nuevo elemento','New item')}</summary><div className={s.fields}><label>{t('Nombre','Name')}<input maxLength={160} value={card.name} onChange={e=>updateCard(kind,i,'name',e.target.value)}/></label><label>{kind==='menus'?t('Categoría','Category'):t('Capacidad de personas','Guest capacity')}<input maxLength={80} value={kind==='menus'?card.category:card.capacity} onChange={e=>updateCard(kind,i,kind==='menus'?'category':'capacity',e.target.value)}/></label></div><label>{t('Descripción pública','Public description')}<textarea maxLength={1000} value={card.description} onChange={e=>updateCard(kind,i,'description',e.target.value)}/></label>{kind==='menus'&&<label>{t('Precio público (vacío = Consultar precio)','Public price (blank = Ask for pricing)')}<input maxLength={50} value={card.price} onChange={e=>updateCard(kind,i,'price',e.target.value)}/></label>}{imageInput(t('Fotografía','Photo'),card.image,path=>updateCard(kind,i,'image',path))}<button type="button" onClick={()=>set(kind,content[kind].filter((_,n)=>i!==n))}>{t('Quitar de la página','Remove from page')}</button></details>)}</>;
 return <section className={s.panel} translate="no"><div className={s.row}><div><h2>{t('Su página pública','Your public page')}</h2><p>{t('Un enlace para sus redes, menús y solicitudes de eventos.','One link for your social profiles, menus and event requests.')}</p></div><span className={s.badge}>{savedPublished?t('Publicada','Published'):t('Sin publicar','Unpublished')}</span></div>
 <div className={s.steps}>{[t('1 · Contenido','1 · Content'),t('2 · Contacto','2 · Contact'),t('3 · Publicar','3 · Publish')].map((label,i)=><button type="button" key={i} className={step===i?s.active:''} onClick={()=>setStep(i)}>{label}</button>)}</div>
 {error&&<div role="alert" className={s.error}>{error}<button type="button" onClick={()=>{if(!loaded||baseline===snapshot||window.confirm(t('¿Descartar cambios y recargar?','Discard changes and reload?')))void load()}}>{t('Recargar','Reload')}</button></div>}{notice&&<p role="status">{notice}</p>}
 {!loaded?<p>{busy?t('Cargando…','Loading…'):t('Instale SQL 50 para habilitar esta función.','Install SQL 50 to enable this feature.')}</p>:<fieldset disabled={busy} style={{border:0,padding:0,minWidth:0,display:'grid',gap:18}}>
 {step===0&&<><p className={s.muted}>{t('Solo se publica lo que agregue aquí. Las copias pueden editarse sin cambiar cotizaciones guardadas ni precios internos. Revise y vuelva a copiar si cambia su catálogo.','Only content added here is published. Copies can be edited without changing saved quotes or internal prices. Review and copy again when your catalog changes.')}</p><label>{t('Nombre público','Public name')}<input value={content.name} maxLength={160} onChange={e=>set('name',e.target.value)}/></label><label>{t('Descripción de la página pública','Public page description')}<textarea value={content.description} maxLength={1500} placeholder={t('Restaurante de [especialidad] en [ubicación]. Conozca nuestros menús y salones, y solicite una cotización para su próximo evento.','A [cuisine] restaurant in [location]. Explore our menus and spaces, and request a quote for your next event.')} onChange={e=>set('description',e.target.value)}/><small className={s.muted}>{t('Presente su restaurante en 2 o 3 frases: especialidad, ubicación y ocasiones que atiende. Este texto será visible para sus clientes.','Introduce your restaurant in 2 or 3 sentences: cuisine, location and occasions you host. Customers will see this text.')}</small></label><label>{t('Dirección pública','Public address')}<input value={content.address} maxLength={300} onChange={e=>set('address',e.target.value)}/></label><div className={s.fields}><label>{t('Idioma inicial','Default language')}<select value={content.language} onChange={e=>set('language',e.target.value as 'es'|'en')}><option value="es">Español</option><option value="en">English</option></select></label><label>{t('Moneda / símbolo','Currency / symbol')}<input value={content.currency} maxLength={10} onChange={e=>set('currency',e.target.value)}/></label></div>{imageInput(t('Logo','Logo'),content.logo,path=>set('logo',path))}{imageInput(t('Imagen principal','Cover image'),content.cover,path=>set('cover',path))}{cardEditor('menus')}{cardEditor('areas')}
 <h3>{t('Menús PDF','PDF menus')}</h3><p className={s.muted}>{t('Máximo 5 PDF de 3 MB. Se abren solo al solicitarlos. Los archivos son públicos: no suba documentos privados.','Up to 5 PDFs, 3 MB each. Loaded only when opened. Files are public: do not upload private documents.')}</p>{content.pdfs.map((pdf,i)=><div className={s.row} key={pdf.path}><input aria-label={t('Nombre del PDF','PDF title')} value={pdf.name} onChange={e=>set('pdfs',content.pdfs.map((x,n)=>i===n?{...x,name:e.target.value}:x))} maxLength={100}/><a href={publicPdfUrl(pdf.path,pdf.name)} target="_blank" rel="noopener noreferrer">{t('Ver','View')}</a><button type="button" onClick={()=>set('pdfs',content.pdfs.filter((_,n)=>i!==n))}>{t('Quitar','Remove')}</button></div>)}{content.pdfs.length<5&&<input aria-label={t('Subir menú PDF','Upload PDF menu')} type="file" accept="application/pdf" onChange={e=>{const file=e.target.files?.[0];void upload(file,path=>setContent(c=>({...c,pdfs:[...c.pdfs,{name:file?.name||'Menu',path}]})));e.target.value=''}}/>}
 <details><summary>{t('Archivos almacenados','Stored files')} · {(assets.reduce((n,a)=>n+a.size,0)/1048576).toFixed(1)} / 20 MB</summary><p className={s.muted}>{t('Quitar del contenido no borra el archivo. Después de guardar, elimine aquí los archivos que ya no usa.','Removing from content does not delete the file. After saving, delete unused files here.')}</p><div className={s.fileList}>{assets.map(a=><div className={s.row} key={a.id}><span>{a.name} · {(a.size/1048576).toFixed(1)} MB</span><button type="button" onClick={()=>void removeAsset(a)}>{t('Eliminar archivo','Delete file')}</button></div>)}</div></details></>}
 {step===1&&<><p>{t('Active los medios que atiende su equipo. El visitante podrá elegir entre ellos.','Enable the methods your team handles. Visitors can choose between them.')}</p>{(['whatsapp','email','phone'] as Channel[]).map(ch=><div className={s.editor} key={ch}><label className={s.choice}><input type="checkbox" checked={content.channels.includes(ch)} onChange={e=>set('channels',e.target.checked?[...content.channels,ch]:content.channels.filter(x=>x!==ch))}/>{ch==='whatsapp'?'WhatsApp':ch==='email'?t('Correo electrónico','Email'):t('Llamada telefónica','Phone call')}</label><input aria-label={ch} type={ch==='email'?'email':'tel'} placeholder={ch==='email'?'eventos@restaurante.com':'+502 … / +1 …'} value={content[ch]} maxLength={ch==='whatsapp'?250:254} onChange={e=>{set(ch,e.target.value);setContactNotice('')}} onBlur={()=>{if(ch==='whatsapp'){const number=whatsappNumber(content.whatsapp);if(number)set('whatsapp',`+${number}`)}}}/>{ch==='whatsapp'&&<><small>{t('Número completo con código de país (+502, +1, +52…). También puede pegar su enlace wa.me. No necesita API.','Full number with country code (+502, +1, +52…). You can also paste your wa.me link. No API needed.')}</small><div className={s.contactActions}><button type="button" onClick={testWhatsApp}>{t('Probar WhatsApp','Test WhatsApp')}</button>{whatsappURL&&<><a href={whatsappURL} target="_blank" rel="noopener noreferrer">{t('Abrir enlace','Open link')}</a><button type="button" onClick={async()=>{try{await navigator.clipboard.writeText(whatsappURL);setContactNotice(t('Enlace de WhatsApp copiado.','WhatsApp link copied.'))}catch{setContactNotice(whatsappURL)}}}>{t('Copiar enlace','Copy link')}</button></>}</div>{whatsappURL&&<small className={s.muted}>{t('Número de destino','Destination number')}: +{whatsappNumber(content.whatsapp)}</small>}{contactNotice&&<p role="status" className={s.muted}>{contactNotice}</p>}</>}
</div>)}<h3>{t('Botones visibles','Visible buttons')}</h3>{(['quotes','reservations','consultations'] as const).map((key,i)=><label className={s.choice} key={key}><input type="checkbox" checked={content[key]} onChange={e=>set(key,e.target.checked)}/>{[t('Cotizar evento → formulario y buzón','Event quote → form and inbox'),t('Solicitar reserva → medio de contacto','Request reservation → contact method'),t('Consultas → medio de contacto','Questions → contact method')][i]}</label>)}<p className={s.muted}>{t('WhatsApp y correo abren la aplicación correspondiente. No registran conversaciones ni reservas automáticamente. El equipo confirma las reservas y las ingresa en UnoMesa.','WhatsApp and email open the corresponding app. Conversations and reservations are not automatically recorded. Your team confirms bookings and enters them in UnoMesa.')}</p></>}
 {step===2&&<><label>{t('Su enlace','Your link')}<span>unomesa.com/r/</span><input value={slug} onChange={e=>setSlug(slugFor(e.target.value))} maxLength={64}/></label><label className={s.choice}><input type="checkbox" checked={published} onChange={e=>setPublished(e.target.checked)}/>{t('Habilitar página pública','Enable public page')}</label><p className={s.muted}>{t('Revise la vista previa y guarde para publicar. Si cambia el nombre del enlace, el anterior seguirá funcionando.','Review the preview and save to publish. Old links keep working after a rename.')}</p><div className={s.preview}><RestaurantPublicPage key={content.language} content={cleanContent(content)} slug={slug} preview/></div>{savedPublished&&savedSlug&&<div className={s.editor}><a className={s.link} href={`/r/${savedSlug}`} target="_blank" rel="noopener noreferrer">https://www.unomesa.com/r/{savedSlug}</a><button type="button" onClick={async()=>{try{await navigator.clipboard.writeText(`https://www.unomesa.com/r/${savedSlug}`);setNotice(t('Enlace copiado.','Link copied.'))}catch{setNotice(t('Seleccione el enlace y cópielo.','Select and copy the link.'))}}}>{t('Copiar enlace','Copy link')}</button><PublicPageQr slug={savedSlug} en={en}/></div>}</>}
 <div className={s.row}>{step>0&&<button type="button" onClick={()=>setStep(step-1)}>{t('Anterior','Previous')}</button>}{step<2&&<button type="button" onClick={()=>setStep(step+1)}>{t('Continuar','Continue')}</button>}<button type="button" className="primary" onClick={()=>void save()}>{busy?t('Guardando…','Saving…'):t('Guardar cambios','Save changes')}</button></div></fieldset>}
 </section>;
}
