'use client';
import { useEffect,useRef,useState } from 'react';
import { assetUrl,publicPdfUrl,contactLink,maximumGuests,type PublicContent } from '@/lib/restaurant-public';
import { PublicPdfViewer } from './public-pdf-viewer';
import { ContactLink } from './contact-link';
import { AccessVerification } from './access-verification';
import s from './restaurant-public.module.css';
export function RestaurantPublicPage({slug,content,preview=false}:{slug:string;content:PublicContent;preview?:boolean}){
 const [locale,setLocale]=useState(content.language),[modal,setModal]=useState<''|'quote'|'reserve'|'contact'|'menu'>(''),[token,setToken]=useState(''),[attempt,setAttempt]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(''),[done,setDone]=useState(false),[selectedPdf,setSelectedPdf]=useState<number|null>(null);
 const requestId=useRef(''),lock=useRef(false),dialog=useRef<HTMLElement>(null),en=locale==='en',t=(es:string,eng:string)=>en?eng:es;
 useEffect(()=>{if(!modal)return;const before=document.activeElement as HTMLElement|null,old=document.body.style.overflow;if(!preview)document.body.style.overflow='hidden';dialog.current?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape'&&!lock.current)setModal('');if(e.key==='Tab'){const nodes=[...dialog.current!.querySelectorAll<HTMLElement>('button,a,input,select,textarea,[tabindex="0"]')].filter(x=>x.getClientRects().length&&!(x as HTMLInputElement).disabled);const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}};document.addEventListener('keydown',key);return()=>{document.body.style.overflow=old;document.removeEventListener('keydown',key);before?.focus({preventScroll:true})}},[modal,preview]);
 const contactText=(kind:'reserve'|'contact')=>kind==='reserve'?t('Hola, quisiera solicitar una reservación. Fecha: __ Hora: __ Personas: __ Nombre: __','Hello, I would like to request a reservation. Date: __ Time: __ Guests: __ Name: __'):t('Hola, tengo una consulta.','Hello, I have a question.');
 const menuPdfs=content.pdfs.filter(pdf=>publicPdfUrl(pdf.path,pdf.name));
 const openMenu=(index:number|null=menuPdfs.length===1?0:null)=>{setSelectedPdf(index);setModal('menu')};
 const contactChannels=content.channels.filter(ch=>contactLink(ch,content));
 const contactAction=(kind:'reserve'|'contact',label:string)=>contactChannels.length===1?<ContactLink className={s.button} href={contactLink(contactChannels[0],content,contactText(kind))}>{label}</ContactLink>:<button type="button" onClick={()=>setModal(kind)}>{label}</button>;
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(lock.current||preview)return;lock.current=true;setBusy(true);setError('');requestId.current ||= crypto.randomUUID();const data=Object.fromEntries(new FormData(e.currentTarget));try{const r=await fetch('/api/public-restaurant',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...data,slug,id:requestId.current,captchaToken:token})});const j=await r.json();if(!r.ok){if(r.status===429)throw new Error(t('Espere unos minutos antes de volver a intentar.','Please wait a few minutes before retrying.'));if(j.error==='CAPTCHA')throw new Error(t('Complete la verificación de nuevo.','Please complete verification again.'));throw new Error(t('No se pudo enviar. Revise los datos o contacte directamente al restaurante.','Could not send. Check your details or contact the restaurant directly.'));}setDone(true);}catch(err){setError((err as Error).message);setAttempt(x=>x+1);}finally{lock.current=false;setBusy(false);}}
 const cards=(rows:PublicContent['menus'],areas=false)=><div className={s.grid}>{rows.map((card,i)=><article className={s.card} key={card.id||i}>{assetUrl(card.image)&&<img src={assetUrl(card.image)} alt={card.name} loading="lazy" decoding="async" width="400" height="185"/>}<div>{card.category&&<small>{card.category}</small>}<h3>{card.name}</h3><p>{card.description}</p>{areas?<span className={s.capacityBadge}>{maximumGuests(card.capacity)?`${t('Capacidad máxima','Maximum capacity')}: ${maximumGuests(card.capacity)} ${t('personas','guests')}`:t('Capacidad por confirmar','Capacity to be confirmed')}</span>:<strong>{card.price?`${content.currency} ${card.price}`:t('Consultar precio','Ask for pricing')}</strong>}</div></article>)}</div>;
 return <main className={s.page} lang={locale} translate="no"><div className={s.wrap}>
 <div className={s.top}><small>{t('Su mesa, su manera','Your table, your way')}</small><button type="button" onClick={()=>setLocale(en?'es':'en')} aria-label="Language / Idioma">{en?'Español':'English'}</button></div>
 <section className={s.hero}><div>{assetUrl(content.logo)&&<img className={s.logo} src={assetUrl(content.logo)} alt={content.name} width="76" height="76"/>}<h1>{content.name||t('Su restaurante','Your restaurant')}</h1><p>{content.description}</p><small>{content.address}</small><div className={s.buttons}>{content.quotes&&<button className={s.primary} onClick={()=>{if(!preview){setModal('quote');setError('')}}}>{t('Cotizar mi evento','Plan my event')}</button>}{menuPdfs.length>0?<button type="button" onClick={()=>openMenu()}>{t('Ver menú','View menu')}</button>:content.menus.length>0?<a className={s.button} href="#restaurant-menu">{t('Ver menú','View menu')}</a>:null}{content.reservations&&contactAction('reserve',t('Solicitar reserva','Request a reservation'))}{content.consultations&&contactAction('contact',t('Consultas','Contact us'))}</div></div>{assetUrl(content.cover)&&<img className={s.cover} src={assetUrl(content.cover)} alt={content.name} width="550" height="440" fetchPriority="high"/>}</section>
 {(content.menus.length>0||content.pdfs.length>0)&&<section className={s.section} id="restaurant-menu"><h2>{t('Conozca nuestro menú','Explore our menu')}</h2>{cards(content.menus)}<div className={s.buttons}>{menuPdfs.map((pdf,i)=><button type="button" onClick={()=>openMenu(i)} key={i}>{pdf.name||t('Menú PDF','PDF menu')}</button>)}</div></section>}
 {content.areas.length>0&&<section className={s.section}><h2>{t('Un espacio para cada ocasión','A space for every occasion')}</h2><p>{t('Disponibilidad sujeta a confirmación del restaurante.','Availability must be confirmed by the restaurant.')}</p>{cards(content.areas,true)}</section>}
 <footer className={s.footer}><span>{content.name}</span><a href="https://www.unomesa.com" target="_blank" rel="noopener noreferrer">{t('Gestionado con','Powered by')} <b>UnoMesa</b> ↗</a></footer>
 {modal&&<div className={s.overlay} onClick={e=>{if(e.target===e.currentTarget&&!busy)setModal('')}}><section ref={dialog} tabIndex={-1} className={s.dialog+' '+(modal==='menu'&&selectedPdf!==null?s.pdfDialog:'')} role="dialog" aria-modal="true" aria-labelledby="public-dialog-title"><header><h2 id="public-dialog-title">{modal==='menu'?(selectedPdf!==null?menuPdfs[selectedPdf]?.name||t('Menú PDF','PDF menu'):t('Elija un menú','Choose a menu')):modal==='quote'?t('Cuéntenos su idea','Tell us about your event'):modal==='reserve'?t('Solicitar reserva','Request a reservation'):t('Hablemos','Let’s talk')}</h2><button type="button" disabled={busy} onClick={()=>setModal('')} aria-label={t('Cerrar','Close')}>×</button></header>
 {modal==='menu'?(selectedPdf!==null&&menuPdfs[selectedPdf]?<>{menuPdfs.length>1&&<button type="button" className={s.backMenus} onClick={()=>setSelectedPdf(null)}>← {t('Otros menús','Other menus')}</button>}<PublicPdfViewer key={menuPdfs[selectedPdf].path} href={publicPdfUrl(menuPdfs[selectedPdf].path,menuPdfs[selectedPdf].name)} name={menuPdfs[selectedPdf].name} en={en}/></>:<><p>{t('Seleccione el menú para ver su PDF.','Select a menu to view its PDF.')}</p><div className={s.buttons}>{menuPdfs.map((pdf,i)=><button type="button" key={i} onClick={()=>setSelectedPdf(i)}>{pdf.name||t('Menú PDF','PDF menu')} →</button>)}</div></>):modal==='quote'?(done?<div className={s.success} role="status"><h3>{t('¡Solicitud recibida!','Request received!')}</h3><p>{t('El restaurante le contactará por el medio elegido. Esta solicitud no confirma una reserva ni bloquea un salón.','The restaurant will contact you using your preferred method. This request does not confirm a booking or hold a space.')}</p></div>:<form onSubmit={submit}>
 <div className={s.fields}><label>{t('Nombre','Name')}<input name="name" autoComplete="name" required maxLength={160}/></label><label>{t('Personas','Guests')}<input name="guests" type="number" min={1} max={100000} required/></label><label>{t('Fecha del evento','Event date')}<input name="event_date" type="date" required/></label><label>{t('Hora local del restaurante','Restaurant local time')}<input name="event_time" type="time" required/></label><label>{t('Teléfono con código de país','Phone with country code')}<input name="phone" type="tel" autoComplete="tel" required maxLength={30} placeholder="+502 … / +1 …"/></label><label>{t('Correo electrónico','Email')}<input name="email" type="email" autoComplete="email" required maxLength={254}/></label></div>
 <label>{t('Menú de interés','Menu preference')}<select name="menu" required><option value="advice">{t('Necesito asesoría','I would like advice')}</option>{content.menus.map((m,i)=><option key={i} value={m.name}>{m.name}</option>)}</select></label>
 {content.areas.length>0&&<label>{t('Salón de interés (opcional)','Preferred space (optional)')}<select name="area"><option value="">{t('Sin preferencia','No preference')}</option>{content.areas.map((a,i)=><option key={i} value={a.name}>{a.name}{maximumGuests(a.capacity)?` · ${t('Hasta','Up to')} ${maximumGuests(a.capacity)} ${t('personas','guests')}`:''}</option>)}</select></label>}
 <label>{t('¿Cómo prefiere que le contactemos?','How would you prefer to be contacted?')}<select name="preference" required defaultValue=""><option value="" disabled>{t('Seleccione un medio','Select a method')}</option>{content.channels.map(ch=><option key={ch} value={ch}>{ch==='whatsapp'?'WhatsApp':ch==='email'?t('Correo electrónico','Email'):t('Llamada telefónica','Phone call')}</option>)}</select><small>{t('Si elige WhatsApp, utilice un número que tenga WhatsApp.','If you choose WhatsApp, use a number registered with WhatsApp.')}</small></label>
 <label>{t('Detalles o preguntas (opcional)','Details or questions (optional)')}<textarea name="notes" rows={3} maxLength={2000}/></label><label className={s.hidden} aria-hidden="true">Website<input name="website" tabIndex={-1} autoComplete="off"/></label>
 <small>{t('Al enviar, comparte estos datos con el restaurante para atender su solicitud. No se realizará ningún cobro.','By submitting, you share these details with the restaurant to handle your request. No payment will be charged.')} <a href="/privacidad" target="_blank" rel="noopener noreferrer">{t('Privacidad','Privacy')}</a></small>
 {process.env.NEXT_PUBLIC_TURNSTILE_SITE_KEY&&<AccessVerification key={attempt} siteKey={process.env.NEXT_PUBLIC_TURNSTILE_SITE_KEY} onToken={setToken}/>}{error&&<p className={s.error} role="alert">{error}</p>}<button className={s.primary} disabled={busy||!!process.env.NEXT_PUBLIC_TURNSTILE_SITE_KEY&&!token}>{busy?t('Enviando…','Sending…'):t('Enviar solicitud','Send request')}</button></form>):<><p>{t('Elija cómo contactar al restaurante. Las reservas requieren confirmación.','Choose how to contact the restaurant. Reservations require confirmation.')}</p><div className={s.buttons}>{contactChannels.map(ch=><ContactLink key={ch} className={s.button} href={contactLink(ch,content,contactText(modal==='reserve'?'reserve':'contact'))}>{ch==='whatsapp'?'WhatsApp':ch==='email'?t('Correo','Email'):t('Llamar','Call')}</ContactLink>)}{!contactChannels.length&&<p role="status">{t('El restaurante aún no ha configurado un medio de contacto válido.','The restaurant has not configured a valid contact method yet.')}</p>}</div></>}
 </section></div>}
 </div></main>;
}
