'use client';
import { useCallback,useEffect,useRef,useState } from 'react';
import { supabase } from '@/lib/supabase';
import { ContactLink } from './contact-link';
import { contactLink,publicProblem } from '@/lib/restaurant-public';
import { useRefreshTask } from './pull-refresh';
import { useModulePending } from './presentation-loading';
import { AppRecord,useAppMode } from './app-context';
import s from './restaurant-public.module.css';
export type PublicRequest={id:string;created_at:string;name:string;phone:string;email:string;event_date:string;event_time:string;guests:number;menu:string;area:string;notes:string;preference:'whatsapp'|'phone'|'email';status:string;quote_id:string|null;revision:number};
export function PublicRequestNotice({restaurantId,en,onOpen}:{restaurantId:string;en:boolean;onOpen:()=>void}){
 const [count,setCount]=useState(0);useEffect(()=>{let live=true,working=false;const load=async()=>{if(document.hidden||working)return;working=true;try{const r=await supabase.rpc('v2_public_unread',{p_restaurant:restaurantId});if(live&&!r.error)setCount(Number(r.data)||0)}finally{working=false}};void load();const timer=setInterval(load,60000);window.addEventListener('unomesa:public-request',load);document.addEventListener('visibilitychange',load);return()=>{live=false;clearInterval(timer);window.removeEventListener('unomesa:public-request',load);document.removeEventListener('visibilitychange',load)}},[restaurantId]);
 return count>0?<div className="moduleNotice" role="status" translate="no"><b>{count>=99?'99+':count} {en?(count===1?'new event request':'new event requests'):(count===1?'solicitud nueva de evento':'solicitudes nuevas de eventos')}</b><button type="button" className="secondary" onClick={onOpen}>{en?'Open inbox':'Abrir buzón'}</button></div>:null;
}
export function PublicInbox({restaurantId,en,canEdit,onQuote,onView}:{restaurantId:string;en:boolean;canEdit:boolean;onQuote:(request:PublicRequest)=>void;onView:(id:string)=>void}){
 const app=useAppMode(),t=(es:string,eng:string)=>en?eng:es;
 const [rows,setRows]=useState<PublicRequest[]>([]),[filter,setFilter]=useState('new'),[cursor,setCursor]=useState<{date:string;id:string}|null>(null),[history,setHistory]=useState<({date:string;id:string}|null)[]>([]),[more,setMore]=useState(false),[busy,setBusy]=useState(true),[error,setError]=useState(''),[saving,setSaving]=useState('');const generation=useRef(0),mutation=useRef(false);
 const load=useCallback(async()=>{const current=++generation.current;setBusy(true);setError('');const r=await supabase.rpc('v2_public_inbox',{p_restaurant:restaurantId,p_status:filter,p_before:cursor?.date||null,p_before_id:cursor?.id||null});if(current!==generation.current)return;if(r.error)setError(publicProblem(r.error,en));else{setRows((r.data||[]).slice(0,25));setMore(r.data?.length>25)}setBusy(false)},[restaurantId,filter,cursor,en]);
 useEffect(()=>{void load();return()=>{generation.current++}},[load]);useRefreshTask(load);useModulePending(busy&&!rows.length);
 async function status(row:PublicRequest,next:string){if(mutation.current)return;mutation.current=true;setSaving(row.id);setError('');try{const r=await supabase.rpc('v2_public_request_update',{p_restaurant:restaurantId,p_id:row.id,p_revision:row.revision,p_status:next});if(r.error)throw r.error;window.dispatchEvent(new Event('unomesa:public-request'));await load();}catch(e){setError(publicProblem(e,en))}finally{setSaving('');mutation.current=false;}}
 const label=(status:string)=>({new:t('Nueva','New'),contacted:t('En atención','In progress'),quoted:t('Cotizada','Quoted'),archived:t('Archivada','Archived')}[status]||status);
 const detail=(r:PublicRequest)=><><p><b>{t('Fecha y hora','Date and time')}:</b> {r.event_date} · {r.event_time.slice(0,5)} · {r.guests} {t('personas','guests')}</p><p><b>{t('Menú','Menu')}:</b> {r.menu==='advice'?t('Necesita asesoría','Needs advice'):r.menu}</p><p><b>{t('Salón','Space')}:</b> {r.area||t('Sin preferencia','No preference')}</p><p><b>{t('Contacto preferido','Preferred contact')}:</b> {r.preference==='whatsapp'?'WhatsApp':r.preference==='email'?t('Correo','Email'):t('Llamada','Phone call')}</p><p>{r.phone} · {r.email}</p>{r.notes&&<p>{r.notes}</p>}<small>{t('Recibida','Received')}: {new Date(r.created_at).toLocaleString(en?'en-US':'es-GT')}</small></>;
 const actions=(r:PublicRequest)=><div className={s.row}><ContactLink className="secondary" href={contactLink(r.preference,{phone:r.phone,whatsapp:r.phone,email:r.email},t(`Hola ${r.name}, recibimos su solicitud de evento para ${r.event_date}.`,`Hello ${r.name}, we received your event request for ${r.event_date}.`))}>{r.preference==='whatsapp'?t('Abrir WhatsApp','Open WhatsApp'):r.preference==='email'?t('Escribir correo','Write email'):t('Llamar','Call')}</ContactLink>{r.quote_id?<button type="button" onClick={()=>onView(r.quote_id!)}>{t('Ver cotización','View quote')}</button>:canEdit&&<button className="primary" type="button" disabled={!!saving} onClick={()=>onQuote(r)}>{t('Crear cotización','Create quote')}</button>}{canEdit&&<><button type="button" disabled={!!saving} onClick={()=>void status(r,r.status==='new'?'contacted':'new')}>{r.status==='new'?t('Marcar en atención','Mark in progress'):t('Volver a nueva','Mark new')}</button><button type="button" disabled={!!saving} onClick={()=>void status(r,r.status==='archived'?'new':'archived')}>{r.status==='archived'?t('Restaurar','Restore'):t('Archivar','Archive')}</button></>}</div>;
 return <section className={s.panel} translate="no"><div className={s.row}><div><h2>{t('Buzón de solicitudes','Request inbox')}</h2><p>{t('Solicitudes de su página pública. No confirman reservas.','Requests from your public page. These do not confirm bookings.')}</p></div><button type="button" disabled={busy} onClick={()=>void load()}>{t('Actualizar','Refresh')}</button></div><label>{t('Mostrar','Show')}<select value={filter} onChange={e=>{setFilter(e.target.value);setHistory([]);setCursor(null)}}>{['new','contacted','quoted','archived','all'].map(x=><option value={x} key={x}>{x==='all'?t('Todas','All'):label(x)}</option>)}</select></label>{error&&<p role="alert" className={s.error}>{error}</p>}
 <div className={s.inbox} aria-busy={busy}>{!busy&&!error&&!rows.length&&<div className={s.empty}>{t('No hay solicitudes en esta sección. Comparta su enlace desde Configuración → Página pública.','No requests in this section. Share your link from Settings → Public page.')}</div>}{rows.map(r=>app?<AppRecord key={r.id} title={r.name} subtitle={`${r.event_date} · ${r.event_time.slice(0,5)} · ${r.guests}`} badge={<span className={s.badge}>{label(r.status)}</span>} actions={actions(r)}><div className={s.request}>{detail(r)}</div></AppRecord>:<article className={s.request} key={r.id}><div className={s.row}><h3>{r.name}</h3><span className={s.badge}>{label(r.status)}</span></div>{detail(r)}{actions(r)}</article>)}</div>
 <div className={s.row}><button disabled={busy||!history.length} onClick={()=>{setCursor(history.at(-1)||null);setHistory(h=>h.slice(0,-1))}}>{t('Anterior','Previous')}</button><small>{t('Página','Page')} {history.length+1} · {rows.length}</small><button disabled={busy||!more} onClick={()=>{const last=rows.at(-1);if(last){setHistory(h=>[...h,cursor]);setCursor({date:last.created_at,id:last.id})}}}>{t('Siguiente','Next')}</button></div><p className={s.muted}>{t('Responder abre WhatsApp, correo o teléfono; UnoMesa no envía mensajes automáticamente. Para enviar la cotización, abra Ver cotización, descargue su PDF y adjúntelo en la conversación.','Reply opens WhatsApp, email or phone; UnoMesa does not send automatically. To send a quote, open View quote, download its PDF and attach it to the conversation.')}</p></section>;
}
