"use client";
import {useState} from 'react';
import {ArrowRight,Check,Layers,LayoutGrid,Users} from 'lucide-react';
import styles from './landing-floor-plan.module.css';
type SampleTable={id:number;seats:number;round?:boolean};
const rooms=[
 {id:'olive',level:1,es:'Salón Olivo',en:'Olive dining room',tables:[{id:1,seats:2,round:true},{id:2,seats:4},{id:3,seats:4},{id:4,seats:4},{id:5,seats:6},{id:6,seats:4,round:true}]},
 {id:'garden',level:1,es:'Terraza Jardín',en:'Garden terrace',tables:[{id:7,seats:4},{id:8,seats:4,round:true},{id:9,seats:4},{id:10,seats:2,round:true}]},
 {id:'oak',level:1,es:'Privado Roble',en:'Oak private room',tables:[{id:11,seats:12}]},
 {id:'view',level:2,es:'Salón Mirador',en:'Skyline dining room',tables:[{id:12,seats:4},{id:13,seats:4},{id:14,seats:6,round:true},{id:15,seats:4}]},
 {id:'lounge',level:2,es:'Lounge Ámbar',en:'Amber lounge',tables:[{id:16,seats:4,round:true},{id:17,seats:4,round:true}]},
];
const bookings=[{id:'b1',table:2,name:'Valeria Ríos',guests:4,time:'19:00',enTime:'7:00 PM',status:'seated',quote:false},{id:'b2',table:5,name:'Grupo Altura',guests:6,time:'19:30',enTime:'7:30 PM',status:'reserved',quote:true},{id:'b3',table:11,name:'Norte Studio',guests:12,time:'20:00',enTime:'8:00 PM',status:'reserved',quote:true},{id:'b4',table:2,name:'Daniela Fuentes',guests:4,time:'21:30',enTime:'9:30 PM',status:'reserved',quote:false},{id:'b5',table:14,name:'Familia Navarro',guests:6,time:'20:00',enTime:'8:00 PM',status:'reserved',quote:false}];
/** Public illustration only. Sample names and selections never access restaurant data. */
export function LandingFloorPlan({en,onStart,signupEnabled}:{en:boolean;onStart:()=>void;signupEnabled:boolean}){
 const [level,setLevel]=useState(1),[selected,setSelected]=useState<number|null>(null),say=(es:string,eng:string)=>en?eng:es;
 const visible=rooms.filter(room=>room.level===level),tables=visible.flatMap(r=>r.tables),rows=bookings.filter(b=>tables.some(t=>t.id===b.table)&&(!selected||b.table===selected));
 const name=(id:number)=>(en?'T':'M')+id;
 return <section className={styles.section} id="plano" aria-labelledby="landing-floor-title">
  <div className={styles.intro}><div><span className={styles.kicker}><LayoutGrid size={16}/>{say('Plano de mesas · Todos los planes','Floor plan · Every plan')}</span><h2 id="landing-floor-title">{say('Cada mesa, cada evento, en su lugar.','Every table. Every event. In place.')}</h2><p>{say('Vea sus salones y niveles en un solo mapa. Reserve una mesa o un salón completo, consulte su agenda y mantenga conectadas las cotizaciones y reservaciones.','See your rooms and floors in one map. Book a table or an entire room, check its schedule, and keep quotes and reservations connected.')}</p></div><button type="button" className="primary" onClick={onStart}>{say(signupEnabled?'Probar el plano gratis':'Iniciar sesión',signupEnabled?'Try the floor plan free':'Sign in')}<ArrowRight size={18}/></button></div>
  <figure className={styles.preview}><figcaption><span className={styles.sampleBrand}>Casa Olivo <small>{say('Restaurante de ejemplo','Sample restaurant')}</small></span><span className={styles.sampleBadge}>{say('Vista interactiva · Datos ficticios','Interactive preview · Sample data')}</span></figcaption>
   <div className={styles.topbar}><div role="group" aria-label={say('Niveles del ejemplo','Sample floors')}>{[1,2].map(n=><button type="button" key={n} aria-pressed={level===n} onClick={()=>{setLevel(n);setSelected(null)}}><Layers size={15}/>{say('Nivel','Floor')} {n}</button>)}</div><span>{tables.length} {say('mesas','tables')}<i/> {tables.reduce((n,t)=>n+t.seats,0)} {say('lugares','seats')}</span></div>
   <div className={styles.workspace}><div className={styles.map}><div className={`${styles.rooms} ${level===2?styles.secondFloor:''}`}>{visible.map(room=><section key={room.id} className={`${styles.room} ${room.id==='olive'?styles.mainRoom:''} ${room.id==='oak'?styles.privateRoom:''}`}><header><b>{en?room.en:room.es}</b><small>{room.tables.length} {say('mesas','tables')}</small></header><div className={styles.tables}>{room.tables.map((table:SampleTable)=>{const booked=bookings.filter(b=>b.table===table.id),state=booked.some(b=>b.status==='seated')?'seated':booked.length?'reserved':'free';return <button type="button" key={table.id} className={`${styles.table} ${table.round?styles.round:''} ${styles[state]} ${selected===table.id?styles.selected:''} ${table.seats>=10?styles.long:''}`} aria-pressed={selected===table.id} aria-label={`${en?room.en:room.es} · ${name(table.id)} · ${table.seats} ${say('lugares','seats')} · ${booked.length} ${say('reservas','reservations')}`} onClick={()=>setSelected(selected===table.id?null:table.id)}><b>{name(table.id)}</b><small>{booked.length?`${booked[0].guests}p · ${en?booked[0].enTime:booked[0].time}`:`${table.seats} ${say('lugares','seats')}`}</small>{booked.length>1&&<em>+{booked.length-1}</em>}</button>})}</div></section>)}</div><div className={styles.legend}><span><i className={styles.free}/>{say('Disponible','Available')}</span><span><i className={styles.reserved}/>{say('Reservada','Reserved')}</span><span><i className={styles.seated}/>{say('En mesa','Seated')}</span></div><p className={styles.hint}>{say('Toque una mesa para explorar su agenda de ejemplo.','Tap a table to explore its sample schedule.')}</p></div>
    <aside className={styles.agenda} aria-label={say('Reservaciones de ejemplo','Sample reservations')}><header><b>{selected?`${say('Mesa','Table')} ${selected}`:say('Agenda del salón','Dining room schedule')}</b>{selected?<button type="button" onClick={()=>setSelected(null)}>{say('Ver todas','View all')}</button>:<span>{rows.length}</span>}</header><div className={styles.bookings} aria-live="polite">{rows.length?rows.map(b=>{const room=rooms.find(r=>r.tables.some(t=>t.id===b.table))!;return <article key={b.id}><div><strong>{en?b.enTime:b.time}</strong><span><Users size={13}/>{b.guests}</span></div><b>{b.name}</b><small>{en?room.en:room.es} · {b.table===11?say('Salón completo','Entire room'):name(b.table)}</small><span className={styles.status}>{b.status==='seated'?say('En mesa','Seated'):say('Confirmada','Confirmed')}</span>{b.quote&&<small className={styles.linked}><Check size={12}/>{say('Cotización vinculada','Quote linked')}</small>}</article>}):<p className={styles.empty}>{say('Sin reservas en esta mesa del ejemplo.','No sample bookings for this table.')}</p>}</div></aside>
   </div>
  </figure>
  <ul className={styles.features}>{[
   [say('Su distribución, a su manera','Your layout, your way'),say('Áreas, varios niveles y mesas con tamaño, forma y posición ajustables.','Rooms, multiple floors, and tables with adjustable size, shape and position.')],
   [say('Reserva desde donde trabaja','Book where you work'),say('Plano y formulario comparten la misma selección. Vincule reservas y cotizaciones al mismo evento.','The map and form share one selection. Link reservations and quotes to the same event.')],
   [say('Comparta el servicio en PDF','Share your service as a PDF'),say('Descargue o imprima el plano, las reservaciones o ambos, con el detalle que su equipo necesita.','Download or print the map, reservations or both, with the details your team needs.')],
  ].map(([title,body])=><li key={title}><Check size={18}/><div><h3>{title}</h3><p>{body}</p></div></li>)}</ul>
  <p className={styles.availability}>{say('Incluido en Basic, Intermediate y Advanced. Disponible en computadora, tablet y móvil.','Included in Basic, Intermediate and Advanced. Available on desktop, tablet and mobile.')}</p>
 </section>;
}
